// @ts-nocheck
import type { NotificationTemplate, NotificationEvent } from "@/lib/types"

export const mockNotificationTemplates: NotificationTemplate[] = [
  {
    id: "nt-001",
    trigger: "order_confirmed",
    name: "Order Confirmation",
    subject: "Order {{orderNumber}} Confirmed",
    bodyHtml: "<p>Dear {{customerName}},</p><p>Thank you for your order <strong>{{orderNumber}}</strong>. We have confirmed your order and production will begin shortly.</p><p><strong>Estimated delivery:</strong> {{dueDate}}</p><p>You can track your order status in your customer portal.</p><p>Best regards,<br/>GelatoConnect Production Team</p>",
    isActive: true,
    variables: ["customerName", "orderNumber", "dueDate", "portalUrl"],
  },
  {
    id: "nt-002",
    trigger: "file_received",
    name: "File Received Confirmation",
    subject: "Files received for order {{orderNumber}}",
    bodyHtml: "<p>Dear {{customerName}},</p><p>We have received your artwork files for order <strong>{{orderNumber}}</strong>.</p><p><strong>File status:</strong> {{fileStatus}}</p><p>Our prepress team will review the files and notify you of any issues.</p><p>Best regards,<br/>GelatoConnect Prepress Team</p>",
    isActive: true,
    variables: ["customerName", "orderNumber", "fileStatus"],
  },
  {
    id: "nt-003",
    trigger: "proof_ready",
    name: "Proof Ready for Approval",
    subject: "Proof ready for order {{orderNumber}}",
    bodyHtml: "<p>Dear {{customerName}},</p><p>Your proof for order <strong>{{orderNumber}}</strong> is ready for review.</p><p>Please log in to your portal to approve or request changes.</p><p><a href=\"{{proofUrl}}\">View Proof</a></p><p>Best regards,<br/>GelatoConnect Prepress Team</p>",
    isActive: true,
    variables: ["customerName", "orderNumber", "proofUrl"],
  },
  {
    id: "nt-004",
    trigger: "proof_reminder",
    name: "Proof Approval Reminder",
    subject: "Reminder: Proof awaiting approval — {{orderNumber}}",
    bodyHtml: "<p>Dear {{customerName}},</p><p>This is a friendly reminder that the proof for order <strong>{{orderNumber}}</strong> is still awaiting your approval.</p><p>To avoid delays to your delivery date, please review and approve the proof at your earliest convenience.</p><p><a href=\"{{proofUrl}}\">View Proof</a></p><p>Best regards,<br/>GelatoConnect Production Team</p>",
    isActive: true,
    variables: ["customerName", "orderNumber", "proofUrl"],
  },
  {
    id: "nt-005",
    trigger: "production_started",
    name: "Production Started",
    subject: "Production started for order {{orderNumber}}",
    bodyHtml: "<p>Dear {{customerName}},</p><p>Great news! Production has started on your order <strong>{{orderNumber}}</strong>.</p><p><strong>Product:</strong> {{productName}}<br/><strong>Quantity:</strong> {{quantity}}<br/><strong>Estimated completion:</strong> {{estimatedCompletion}}</p><p>Best regards,<br/>GelatoConnect Production Team</p>",
    isActive: true,
    variables: ["customerName", "orderNumber", "productName", "quantity", "estimatedCompletion"],
  },
  {
    id: "nt-006",
    trigger: "shipped",
    name: "Shipment Notification",
    subject: "Your order {{orderNumber}} has shipped",
    bodyHtml: "<p>Dear {{customerName}},</p><p>Your order <strong>{{orderNumber}}</strong> has been shipped!</p><p><strong>Carrier:</strong> {{carrier}}<br/><strong>Tracking number:</strong> {{trackingNumber}}<br/><strong>Estimated delivery:</strong> {{estimatedDelivery}}</p><p><a href=\"{{trackingUrl}}\">Track Your Shipment</a></p><p>Best regards,<br/>GelatoConnect Logistics Team</p>",
    isActive: true,
    variables: ["customerName", "orderNumber", "carrier", "trackingNumber", "estimatedDelivery", "trackingUrl"],
  },
  {
    id: "nt-007",
    trigger: "invoice_sent",
    name: "Invoice Sent",
    subject: "Invoice {{invoiceNumber}} for order {{orderNumber}}",
    bodyHtml: "<p>Dear {{customerName}},</p><p>Please find attached invoice <strong>{{invoiceNumber}}</strong> for order {{orderNumber}}.</p><p><strong>Amount due:</strong> {{currency}} {{amountDue}}<br/><strong>Payment due:</strong> {{dueDate}}</p><p>Payment details are included in the attached invoice.</p><p>Best regards,<br/>GelatoConnect Accounts Team</p>",
    isActive: true,
    variables: ["customerName", "orderNumber", "invoiceNumber", "currency", "amountDue", "dueDate"],
  },
  {
    id: "nt-008",
    trigger: "payment_received",
    name: "Payment Received",
    subject: "Payment received — Invoice {{invoiceNumber}}",
    bodyHtml: "<p>Dear {{customerName}},</p><p>Thank you! We have received your payment of <strong>{{currency}} {{amount}}</strong> for invoice <strong>{{invoiceNumber}}</strong>.</p><p><strong>Payment method:</strong> {{paymentMethod}}<br/><strong>Reference:</strong> {{reference}}</p><p>Best regards,<br/>GelatoConnect Accounts Team</p>",
    isActive: true,
    variables: ["customerName", "invoiceNumber", "currency", "amount", "paymentMethod", "reference"],
  },
]

export const mockNotificationEvents: NotificationEvent[] = [
  { id: "nev-001", trigger: "order_confirmed", sentAt: "2025-09-05T10:15:00Z", recipientEmail: "h.weber@acme-corp.de", recipientName: "Hans Weber", subject: "Order ORD-2025-001 Confirmed", status: "delivered" },
  { id: "nev-002", trigger: "file_received", sentAt: "2025-09-05T11:00:00Z", recipientEmail: "h.weber@acme-corp.de", recipientName: "Hans Weber", subject: "Files received for order ORD-2025-001", status: "delivered" },
  { id: "nev-003", trigger: "proof_ready", sentAt: "2025-09-06T14:00:00Z", recipientEmail: "h.weber@acme-corp.de", recipientName: "Hans Weber", subject: "Proof ready for order ORD-2025-001", status: "opened" },
  { id: "nev-004", trigger: "production_started", sentAt: "2025-09-08T07:30:00Z", recipientEmail: "h.weber@acme-corp.de", recipientName: "Hans Weber", subject: "Production started for order ORD-2025-001", status: "delivered" },
  { id: "nev-005", trigger: "shipped", sentAt: "2025-09-20T14:30:00Z", recipientEmail: "h.weber@acme-corp.de", recipientName: "Hans Weber", subject: "Your order ORD-2025-001 has shipped", status: "delivered" },
  { id: "nev-006", trigger: "invoice_sent", sentAt: "2025-09-22T10:30:00Z", recipientEmail: "accounts@acme-corp.de", recipientName: "Acme Accounts", subject: "Invoice INV-2025-001 for order ORD-2025-001", status: "delivered" },
  { id: "nev-007", trigger: "payment_received", sentAt: "2025-10-05T09:30:00Z", recipientEmail: "accounts@acme-corp.de", recipientName: "Acme Accounts", subject: "Payment received — Invoice INV-2025-001", status: "delivered" },
  { id: "nev-008", trigger: "order_confirmed", sentAt: "2025-11-10T09:45:00Z", recipientEmail: "j.clarke@printco.co.uk", recipientName: "James Clarke", subject: "Order ORD-2025-002 Confirmed", status: "delivered" },
  { id: "nev-009", trigger: "order_confirmed", sentAt: "2025-10-01T14:30:00Z", recipientEmail: "a.hofmann@brandex.at", recipientName: "Anna Hofmann", subject: "Order ORD-2025-003 Confirmed", status: "delivered" },
  { id: "nev-010", trigger: "proof_ready", sentAt: "2025-10-08T10:00:00Z", recipientEmail: "a.hofmann@brandex.at", recipientName: "Anna Hofmann", subject: "Proof ready for order ORD-2025-003", status: "opened" },
  { id: "nev-011", trigger: "shipped", sentAt: "2025-09-24T09:15:00Z", recipientEmail: "c.laurent@luxe-labels.fr", recipientName: "Camille Laurent", subject: "Your order ORD-2025-005 has shipped", status: "delivered" },
  { id: "nev-012", trigger: "invoice_sent", sentAt: "2025-09-26T10:15:00Z", recipientEmail: "comptabilite@luxe-labels.fr", recipientName: "Luxe Labels Finance", subject: "Invoice INV-2025-002 for order ORD-2025-005", status: "delivered" },
  { id: "nev-013", trigger: "order_confirmed", sentAt: "2025-11-15T14:30:00Z", recipientEmail: "m.virtanen@titanpress.fi", recipientName: "Mika Virtanen", subject: "Order ORD-2025-010 Confirmed", status: "delivered" },
  { id: "nev-014", trigger: "proof_reminder", sentAt: "2025-11-25T09:00:00Z", recipientEmail: "p.dubois@creative-signs.be", recipientName: "Pierre Dubois", subject: "Reminder: Proof awaiting approval — ORD-2025-004", status: "sent" },
  { id: "nev-015", trigger: "invoice_sent", sentAt: "2025-11-01T10:10:00Z", recipientEmail: "laskut@titanpress.fi", recipientName: "Titan Press Finance", subject: "Invoice INV-2025-004 for order ORD-2025-017", status: "delivered" },
  { id: "nev-016", trigger: "invoice_sent", sentAt: "2025-11-01T10:05:00Z", recipientEmail: "billing@metroprint.nl", recipientName: "Metro Print Billing", subject: "Invoice INV-2025-005 for order ORD-2025-007", status: "delivered" },
  { id: "nev-017", trigger: "production_started", sentAt: "2025-11-25T07:30:00Z", recipientEmail: "a.hofmann@brandex.at", recipientName: "Anna Hofmann", subject: "Production started for order ORD-2025-003", status: "delivered" },
  { id: "nev-018", trigger: "shipped", sentAt: "2025-10-28T09:15:00Z", recipientEmail: "m.virtanen@titanpress.fi", recipientName: "Mika Virtanen", subject: "Your order ORD-2025-017 has shipped", status: "failed" },
  { id: "nev-019", trigger: "invoice_sent", sentAt: "2025-11-25T10:20:00Z", recipientEmail: "finance@summitmedia.co.uk", recipientName: "Summit Media Finance", subject: "Invoice INV-2025-007 for order ORD-2025-008", status: "delivered" },
  { id: "nev-020", trigger: "order_confirmed", sentAt: "2025-11-28T09:15:00Z", recipientEmail: "s.keller@apex-packaging.ch", recipientName: "Stefan Keller", subject: "Order ORD-2025-006 Confirmed", status: "delivered" },
]
