// @ts-nocheck
import type { Customer } from "@/lib/types"

export const mockCustomers: Customer[] = [
  {
    id: "acme-corp",
    name: "Acme Corporation",
    currency: "EUR",
    country: "Germany",
    countryFlag: "🇩🇪",
    address: "Industriestraße 42, 80331 München, Germany",
    pricingTier: "Platinum",
    paymentTerms: "Net 30",
    invoiceTrigger: "automatic",
    invoiceEmail: "accounts@acme-corp.de",
    contacts: [
      { id: "cc-acme-1", name: "Hans Weber", email: "h.weber@acme-corp.de", phone: "+49 89 1234567", role: "primary", isPrimary: true },
      { id: "cc-acme-2", name: "Lisa Braun", email: "l.braun@acme-corp.de", phone: "+49 89 1234568", role: "billing", isPrimary: false },
      { id: "cc-acme-3", name: "Karl Müller", email: "k.mueller@acme-corp.de", phone: "+49 89 1234569", role: "production", isPrimary: false },
    ],
    salesRep: "Thomas Fischer",
    estimationEnabled: true,
    notificationPreferences: { orderConfirmation: true, proofReady: true, productionStarted: true, shipped: true, invoiceSent: true },
    notes: [
      { id: "cn-acme-1", text: "Platinum customer since 2021. Prefers uncoated stocks for corporate materials.", author: "Thomas Fischer", createdAt: "2025-01-15T09:00:00Z" },
    ],
    createdAt: "2021-03-10T08:00:00Z",
  },
  {
    id: "printco-ltd",
    name: "PrintCo Ltd",
    currency: "GBP",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    address: "14 Fleet Street, London EC4Y 1AA, United Kingdom",
    pricingTier: "Gold",
    paymentTerms: "Net 30",
    invoiceTrigger: "automatic",
    invoiceEmail: "invoices@printco.co.uk",
    contacts: [
      { id: "cc-printco-1", name: "James Clarke", email: "j.clarke@printco.co.uk", phone: "+44 20 7946 0123", role: "primary", isPrimary: true },
      { id: "cc-printco-2", name: "Sarah Mitchell", email: "s.mitchell@printco.co.uk", phone: "+44 20 7946 0124", role: "billing", isPrimary: false },
    ],
    salesRep: "Emma Thompson",
    estimationEnabled: true,
    notificationPreferences: { orderConfirmation: true, proofReady: true, productionStarted: false, shipped: true, invoiceSent: true },
    notes: [
      { id: "cn-printco-1", text: "Reseller account. Orders high volumes of business cards and leaflets.", author: "Emma Thompson", createdAt: "2025-02-20T10:30:00Z" },
    ],
    createdAt: "2022-06-15T10:00:00Z",
  },
  {
    id: "brandex",
    name: "BrandEx GmbH",
    currency: "EUR",
    country: "Austria",
    countryFlag: "🇦🇹",
    address: "Kärntner Straße 18, 1010 Wien, Austria",
    pricingTier: "Gold",
    paymentTerms: "Net 45",
    invoiceTrigger: "consolidated",
    invoiceEmail: "finance@brandex.at",
    contacts: [
      { id: "cc-brandex-1", name: "Anna Hofmann", email: "a.hofmann@brandex.at", phone: "+43 1 5123456", role: "primary", isPrimary: true },
      { id: "cc-brandex-2", name: "Markus Steiner", email: "m.steiner@brandex.at", phone: "+43 1 5123457", role: "shipping", isPrimary: false },
    ],
    salesRep: "Thomas Fischer",
    estimationEnabled: true,
    notificationPreferences: { orderConfirmation: true, proofReady: true, productionStarted: true, shipped: true, invoiceSent: true },
    notes: [
      { id: "cn-brandex-1", text: "Branding agency. Often requires Pantone spot colour matching.", author: "Thomas Fischer", createdAt: "2025-04-10T14:00:00Z" },
    ],
    createdAt: "2023-01-20T09:00:00Z",
  },
  {
    id: "creative-signs",
    name: "Creative Signs NV",
    currency: "EUR",
    country: "Belgium",
    countryFlag: "🇧🇪",
    address: "Rue de la Loi 120, 1000 Bruxelles, Belgium",
    pricingTier: "Silver",
    paymentTerms: "Net 30",
    invoiceTrigger: "automatic",
    invoiceEmail: "ap@creative-signs.be",
    contacts: [
      { id: "cc-cs-1", name: "Pierre Dubois", email: "p.dubois@creative-signs.be", phone: "+32 2 505 1234", role: "primary", isPrimary: true },
    ],
    salesRep: "Emma Thompson",
    estimationEnabled: true,
    notificationPreferences: { orderConfirmation: true, proofReady: true, productionStarted: false, shipped: true, invoiceSent: true },
    notes: [],
    createdAt: "2023-05-12T11:00:00Z",
  },
  {
    id: "metro-print",
    name: "Metro Print Services",
    currency: "EUR",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    address: "Herengracht 200, 1016 BS Amsterdam, Netherlands",
    pricingTier: "Standard",
    paymentTerms: "Net 15",
    invoiceTrigger: "automatic",
    invoiceEmail: "billing@metroprint.nl",
    contacts: [
      { id: "cc-mp-1", name: "Jan de Vries", email: "j.devries@metroprint.nl", phone: "+31 20 555 0101", role: "primary", isPrimary: true },
      { id: "cc-mp-2", name: "Anouk Bakker", email: "a.bakker@metroprint.nl", phone: "+31 20 555 0102", role: "production", isPrimary: false },
    ],
    salesRep: "Thomas Fischer",
    estimationEnabled: false,
    notificationPreferences: { orderConfirmation: true, proofReady: false, productionStarted: false, shipped: true, invoiceSent: true },
    notes: [],
    createdAt: "2024-02-01T08:00:00Z",
  },
  {
    id: "luxe-labels",
    name: "Luxe Labels SA",
    currency: "EUR",
    country: "France",
    countryFlag: "🇫🇷",
    address: "25 Avenue des Champs-Élysées, 75008 Paris, France",
    pricingTier: "Platinum",
    paymentTerms: "Net 45",
    invoiceTrigger: "consolidated",
    invoiceEmail: "comptabilite@luxe-labels.fr",
    contacts: [
      { id: "cc-ll-1", name: "Camille Laurent", email: "c.laurent@luxe-labels.fr", phone: "+33 1 42 68 1234", role: "primary", isPrimary: true },
      { id: "cc-ll-2", name: "Philippe Martin", email: "p.martin@luxe-labels.fr", phone: "+33 1 42 68 1235", role: "billing", isPrimary: false },
    ],
    salesRep: "Emma Thompson",
    estimationEnabled: true,
    notificationPreferences: { orderConfirmation: true, proofReady: true, productionStarted: true, shipped: true, invoiceSent: true },
    notes: [
      { id: "cn-ll-1", text: "Premium wine and spirits label client. Requires foil stamping and embossing on most jobs.", author: "Emma Thompson", createdAt: "2025-03-05T16:00:00Z" },
    ],
    createdAt: "2022-09-01T10:00:00Z",
  },
  {
    id: "apex-packaging",
    name: "Apex Packaging AG",
    currency: "EUR",
    country: "Switzerland",
    countryFlag: "🇨🇭",
    address: "Bahnhofstrasse 50, 8001 Zürich, Switzerland",
    pricingTier: "Gold",
    paymentTerms: "Net 30",
    invoiceTrigger: "automatic",
    invoiceEmail: "rechnungen@apex-packaging.ch",
    contacts: [
      { id: "cc-ap-1", name: "Stefan Keller", email: "s.keller@apex-packaging.ch", phone: "+41 44 210 5678", role: "primary", isPrimary: true },
      { id: "cc-ap-2", name: "Monika Frei", email: "m.frei@apex-packaging.ch", phone: "+41 44 210 5679", role: "production", isPrimary: false },
    ],
    salesRep: "Thomas Fischer",
    estimationEnabled: true,
    notificationPreferences: { orderConfirmation: true, proofReady: true, productionStarted: true, shipped: true, invoiceSent: true },
    notes: [
      { id: "cn-ap-1", text: "Specialises in luxury packaging. Always requests FSC-certified stock.", author: "Thomas Fischer", createdAt: "2025-06-01T09:00:00Z" },
    ],
    createdAt: "2023-03-15T08:00:00Z",
  },
  {
    id: "summit-media",
    name: "Summit Media Group",
    currency: "GBP",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    address: "55 Baker Street, London W1U 8EW, United Kingdom",
    pricingTier: "Silver",
    paymentTerms: "Net 30",
    invoiceTrigger: "automatic",
    invoiceEmail: "finance@summitmedia.co.uk",
    contacts: [
      { id: "cc-sm-1", name: "Oliver Grant", email: "o.grant@summitmedia.co.uk", phone: "+44 20 3000 4567", role: "primary", isPrimary: true },
    ],
    salesRep: "Emma Thompson",
    estimationEnabled: true,
    notificationPreferences: { orderConfirmation: true, proofReady: true, productionStarted: false, shipped: true, invoiceSent: true },
    notes: [],
    createdAt: "2024-01-10T10:00:00Z",
  },
  {
    id: "nova-graphics",
    name: "Nova Graphics Srl",
    currency: "EUR",
    country: "Italy",
    countryFlag: "🇮🇹",
    address: "Via della Conciliazione 10, 00193 Roma, Italy",
    pricingTier: "Standard",
    paymentTerms: "Net 60",
    invoiceTrigger: "days_after",
    invoiceEmail: "fatture@novagraphics.it",
    contacts: [
      { id: "cc-ng-1", name: "Marco Rossi", email: "m.rossi@novagraphics.it", phone: "+39 06 6812 3456", role: "primary", isPrimary: true },
      { id: "cc-ng-2", name: "Giulia Bianchi", email: "g.bianchi@novagraphics.it", phone: "+39 06 6812 3457", role: "billing", isPrimary: false },
    ],
    salesRep: "Thomas Fischer",
    estimationEnabled: false,
    notificationPreferences: { orderConfirmation: true, proofReady: false, productionStarted: false, shipped: true, invoiceSent: true },
    notes: [],
    createdAt: "2024-06-20T09:00:00Z",
  },
  {
    id: "titan-press",
    name: "Titan Press OY",
    currency: "EUR",
    country: "Finland",
    countryFlag: "🇫🇮",
    address: "Mannerheimintie 15, 00100 Helsinki, Finland",
    pricingTier: "Silver",
    paymentTerms: "Net 30",
    invoiceTrigger: "automatic",
    invoiceEmail: "laskut@titanpress.fi",
    contacts: [
      { id: "cc-tp-1", name: "Mika Virtanen", email: "m.virtanen@titanpress.fi", phone: "+358 9 123 4567", role: "primary", isPrimary: true },
      { id: "cc-tp-2", name: "Aino Korhonen", email: "a.korhonen@titanpress.fi", phone: "+358 9 123 4568", role: "shipping", isPrimary: false },
    ],
    salesRep: "Emma Thompson",
    estimationEnabled: true,
    notificationPreferences: { orderConfirmation: true, proofReady: true, productionStarted: false, shipped: true, invoiceSent: true },
    notes: [
      { id: "cn-tp-1", text: "Nordic distributor. Requires palletised shipments for all orders over 500 units.", author: "Emma Thompson", createdAt: "2025-05-15T11:00:00Z" },
    ],
    createdAt: "2024-04-01T10:00:00Z",
  },
]
