// @ts-nocheck
import type { JobTicket } from "@/lib/types"

export const mockJobTickets: JobTicket[] = [
  {
    id: "JOB-2025-001",
    orderId: "ORD-2025-001",
    orderNumber: "ORD-2025-001",
    customerName: "Acme Corporation",
    product: "Annual Report A4",
    quantity: 2000,
    status: "Completed",
    workflowTemplateId: "wf-offset",
    steps: [
      { id: "ps-001-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 1", estimatedDuration: 120, actualDuration: 105, startedAt: "2025-09-06T08:00:00Z", completedAt: "2025-09-06T09:45:00Z", operatorName: "Martin Schulz", notes: "All files preflight passed. Imposed for SRA3.", isParallel: false, isOptional: false },
      { id: "ps-001-2", name: "Printing", sequence: 2, status: "completed", assignedStation: "Heidelberg XL-106", estimatedDuration: 480, actualDuration: 510, startedAt: "2025-09-08T07:00:00Z", completedAt: "2025-09-08T15:30:00Z", operatorName: "Klaus Bauer", notes: "Interior + cover sheets. Slight delay on colour matching.", isParallel: false, isOptional: false },
      { id: "ps-001-3", name: "Lamination", sequence: 3, status: "completed", assignedStation: "Laminator L-1", estimatedDuration: 90, actualDuration: 80, startedAt: "2025-09-09T08:00:00Z", completedAt: "2025-09-09T09:20:00Z", operatorName: "Petra Vogel", notes: "Matt lamination on covers.", isParallel: false, isOptional: false },
      { id: "ps-001-4", name: "Cutting", sequence: 4, status: "completed", assignedStation: "Polar 115", estimatedDuration: 60, actualDuration: 55, startedAt: "2025-09-09T10:00:00Z", completedAt: "2025-09-09T10:55:00Z", operatorName: "Erik Hahn", notes: "", isParallel: false, isOptional: false },
      { id: "ps-001-5", name: "Binding", sequence: 5, status: "completed", assignedStation: "Muller Martini", estimatedDuration: 240, actualDuration: 260, startedAt: "2025-09-10T07:00:00Z", completedAt: "2025-09-10T11:20:00Z", operatorName: "Franz Richter", notes: "Perfect binding. Adhesive temperature adjusted mid-run.", isParallel: false, isOptional: false },
      { id: "ps-001-6", name: "QC", sequence: 6, status: "completed", assignedStation: "QC Station", estimatedDuration: 60, actualDuration: 45, startedAt: "2025-09-10T13:00:00Z", completedAt: "2025-09-10T13:45:00Z", operatorName: "Sabine Lehmann", notes: "All checks passed. 12 units rejected (binding defect).", isParallel: false, isOptional: false },
      { id: "ps-001-7", name: "Packaging", sequence: 7, status: "completed", assignedStation: "Packing Area", estimatedDuration: 90, actualDuration: 85, startedAt: "2025-09-10T14:00:00Z", completedAt: "2025-09-10T15:25:00Z", operatorName: "Lukas Maier", notes: "Palletised for Munich. Boxed for London shipment.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-09-05T10:30:00Z", changedBy: "Thomas Fischer", changes: "Initial job ticket created" },
    ],
    currentVersion: 1,
    createdAt: "2025-09-05T10:30:00Z",
    dueDate: "2025-09-25T17:00:00Z",
    priority: "high",
    specialInstructions: "FSC-certified stock. Split delivery: 1500 Munich, 500 London.",
    materials: [
      { id: "mr-001-1", materialId: "mat-silk-170", name: "170gsm Silk Coated", specification: "SRA3 sheets, FSC certified", quantityNeeded: 8500, unit: "sheets", quantityAllocated: 8500, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.12, totalCost: 1020 },
      { id: "mr-001-2", materialId: "mat-silk-350", name: "350gsm Silk Cover", specification: "SRA3 sheets, FSC certified", quantityNeeded: 550, unit: "sheets", quantityAllocated: 550, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.38, totalCost: 209 },
    ],
  },
  {
    id: "JOB-2025-002",
    orderId: "ORD-2025-002",
    orderNumber: "ORD-2025-002",
    customerName: "PrintCo Ltd",
    product: "Business Cards",
    quantity: 50000,
    status: "In Progress",
    workflowTemplateId: "wf-digital",
    steps: [
      { id: "ps-002-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 2", estimatedDuration: 30, actualDuration: 25, startedAt: "2025-11-11T08:00:00Z", completedAt: "2025-11-11T08:25:00Z", operatorName: "Martin Schulz", notes: "Ganged on SRA3.", isParallel: false, isOptional: false },
      { id: "ps-002-2", name: "Printing", sequence: 2, status: "in-progress", assignedStation: "HP Indigo 12000", estimatedDuration: 360, startedAt: "2025-11-28T07:00:00Z", operatorName: "Anna Berger", notes: "Running at 4800 sheets/hr.", isParallel: false, isOptional: false },
      { id: "ps-002-3", name: "Lamination", sequence: 3, status: "pending", estimatedDuration: 120, notes: "Matt lamination both sides.", isParallel: false, isOptional: false },
      { id: "ps-002-4", name: "Cutting", sequence: 4, status: "pending", estimatedDuration: 180, notes: "Cut to 85x55mm. 12-up imposition.", isParallel: false, isOptional: false },
      { id: "ps-002-5", name: "QC", sequence: 5, status: "pending", estimatedDuration: 60, notes: "", isParallel: false, isOptional: false },
      { id: "ps-002-6", name: "Packaging", sequence: 6, status: "pending", estimatedDuration: 120, notes: "Pack in boxes of 250.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-11-10T10:00:00Z", changedBy: "Emma Thompson", changes: "Initial job ticket created" },
    ],
    currentVersion: 1,
    createdAt: "2025-11-10T10:00:00Z",
    dueDate: "2025-12-05T17:00:00Z",
    priority: "normal",
    specialInstructions: "Pack in boxes of 250. Each box labelled with customer name.",
    materials: [
      { id: "mr-002-1", materialId: "mat-silk-400", name: "400gsm Silk Card", specification: "SRA3 sheets", quantityNeeded: 4200, unit: "sheets", quantityAllocated: 4200, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.45, totalCost: 1890 },
    ],
  },
  {
    id: "JOB-2025-003",
    orderId: "ORD-2025-003",
    orderNumber: "ORD-2025-003",
    customerName: "BrandEx GmbH",
    product: "Product Catalogue A4",
    quantity: 5000,
    status: "In Progress",
    workflowTemplateId: "wf-offset",
    steps: [
      { id: "ps-003-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 1", estimatedDuration: 180, actualDuration: 200, startedAt: "2025-10-05T08:00:00Z", completedAt: "2025-10-05T11:20:00Z", operatorName: "Martin Schulz", notes: "96 pages imposed. CTP plates made.", isParallel: false, isOptional: false },
      { id: "ps-003-2", name: "Printing", sequence: 2, status: "in-progress", assignedStation: "Heidelberg XL-106", estimatedDuration: 960, startedAt: "2025-11-25T07:00:00Z", operatorName: "Klaus Bauer", notes: "5-colour (CMYK + Pantone 186C). Interior sheets complete, running covers.", isParallel: false, isOptional: false },
      { id: "ps-003-3", name: "Spot UV", sequence: 3, status: "pending", estimatedDuration: 120, notes: "Spot UV on cover only.", isParallel: false, isOptional: false, vendorId: "vendor-finishpro" },
      { id: "ps-003-4", name: "Cutting", sequence: 4, status: "pending", estimatedDuration: 90, notes: "", isParallel: false, isOptional: false },
      { id: "ps-003-5", name: "Binding", sequence: 5, status: "pending", estimatedDuration: 360, notes: "Perfect binding.", isParallel: false, isOptional: false },
      { id: "ps-003-6", name: "QC", sequence: 6, status: "pending", estimatedDuration: 90, notes: "Check Pantone accuracy.", isParallel: false, isOptional: false },
      { id: "ps-003-7", name: "Packaging", sequence: 7, status: "pending", estimatedDuration: 120, notes: "Split delivery to Vienna and Salzburg.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-10-01T15:00:00Z", changedBy: "Thomas Fischer", changes: "Initial job ticket created" },
      { version: 2, changedAt: "2025-10-20T09:00:00Z", changedBy: "Thomas Fischer", changes: "Added Spot UV outsource step" },
    ],
    currentVersion: 2,
    createdAt: "2025-10-01T15:00:00Z",
    dueDate: "2025-12-15T17:00:00Z",
    priority: "high",
    specialInstructions: "Pantone 186C spot colour. Proof approved. Split delivery: 3000 Vienna, 2000 Salzburg.",
    materials: [
      { id: "mr-003-1", materialId: "mat-silk-150", name: "150gsm Silk Coated", specification: "SRA2 sheets", quantityNeeded: 30000, unit: "sheets", quantityAllocated: 30000, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.18, totalCost: 5400 },
      { id: "mr-003-2", materialId: "mat-art-300", name: "300gsm Art Board", specification: "SRA2 sheets", quantityNeeded: 1400, unit: "sheets", quantityAllocated: 1400, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.52, totalCost: 728 },
      { id: "mr-003-3", materialId: "mat-ink-pantone", name: "Pantone 186C Ink", specification: "1kg tin", quantityNeeded: 2, unit: "kg", quantityAllocated: 2, status: "reserved", supplier: "Ink Systems EU", unitCost: 85, totalCost: 170 },
    ],
  },
  {
    id: "JOB-2025-005",
    orderId: "ORD-2025-005",
    orderNumber: "ORD-2025-005",
    customerName: "Luxe Labels SA",
    product: "Wine Labels",
    quantity: 25000,
    status: "Completed",
    workflowTemplateId: "wf-labels",
    steps: [
      { id: "ps-005-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 1", estimatedDuration: 90, actualDuration: 110, startedAt: "2025-08-28T08:00:00Z", completedAt: "2025-08-28T09:50:00Z", operatorName: "Martin Schulz", notes: "Front label: foil + emboss plates prepared. Back label: CMYK CTP.", isParallel: false, isOptional: false },
      { id: "ps-005-2", name: "Printing", sequence: 2, status: "completed", assignedStation: "Heidelberg XL-106", estimatedDuration: 300, actualDuration: 320, startedAt: "2025-09-02T07:00:00Z", completedAt: "2025-09-02T12:20:00Z", operatorName: "Klaus Bauer", notes: "Back labels printed. Front labels base print done.", isParallel: false, isOptional: false },
      { id: "ps-005-3", name: "Foil Stamping", sequence: 3, status: "completed", estimatedDuration: 240, actualDuration: 260, startedAt: "2025-09-03T08:00:00Z", completedAt: "2025-09-03T12:20:00Z", operatorName: "Petra Vogel", notes: "Gold foil applied. Registration checked.", isParallel: false, isOptional: false, vendorId: "vendor-finishpro" },
      { id: "ps-005-4", name: "Embossing", sequence: 4, status: "completed", estimatedDuration: 180, actualDuration: 190, startedAt: "2025-09-04T08:00:00Z", completedAt: "2025-09-04T11:10:00Z", operatorName: "Petra Vogel", notes: "Blind emboss on front labels.", isParallel: false, isOptional: false },
      { id: "ps-005-5", name: "Cutting", sequence: 5, status: "completed", assignedStation: "Polar 115", estimatedDuration: 120, actualDuration: 100, startedAt: "2025-09-05T08:00:00Z", completedAt: "2025-09-05T09:40:00Z", operatorName: "Erik Hahn", notes: "Die-cut to shape.", isParallel: false, isOptional: false },
      { id: "ps-005-6", name: "QC", sequence: 6, status: "completed", assignedStation: "QC Station", estimatedDuration: 90, actualDuration: 75, startedAt: "2025-09-05T10:00:00Z", completedAt: "2025-09-05T11:15:00Z", operatorName: "Sabine Lehmann", notes: "Colour and foil registration checked. 50 units rejected.", isParallel: false, isOptional: false },
      { id: "ps-005-7", name: "Packaging", sequence: 7, status: "completed", assignedStation: "Packing Area", estimatedDuration: 60, actualDuration: 55, startedAt: "2025-09-05T13:00:00Z", completedAt: "2025-09-05T13:55:00Z", operatorName: "Lukas Maier", notes: "Wound on 76mm cores, 1000 per roll.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-08-25T11:00:00Z", changedBy: "Emma Thompson", changes: "Initial job ticket created" },
    ],
    currentVersion: 1,
    createdAt: "2025-08-25T11:00:00Z",
    dueDate: "2025-09-30T17:00:00Z",
    priority: "high",
    specialInstructions: "Colour match to 2021 vintage. Labels on 76mm cores, 1000/roll.",
    materials: [
      { id: "mr-005-1", materialId: "mat-label-textured", name: "Textured Self-Adhesive Label Stock", specification: "Rolls, 250mm wide", quantityNeeded: 120, unit: "metres", quantityAllocated: 120, status: "reserved", supplier: "Avery Dennison", unitCost: 3.50, totalCost: 420 },
    ],
  },
  {
    id: "JOB-2025-007",
    orderId: "ORD-2025-007",
    orderNumber: "ORD-2025-007",
    customerName: "Metro Print Services",
    product: "DL & A5 Flyers",
    quantity: 35000,
    status: "Completed",
    workflowTemplateId: "wf-digital",
    steps: [
      { id: "ps-007-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 2", estimatedDuration: 30, actualDuration: 20, startedAt: "2025-11-16T08:00:00Z", completedAt: "2025-11-16T08:20:00Z", operatorName: "Martin Schulz", notes: "Ganged DL and A5 on SRA3.", isParallel: false, isOptional: false },
      { id: "ps-007-2", name: "Printing", sequence: 2, status: "completed", assignedStation: "Konica Minolta C14000", estimatedDuration: 240, actualDuration: 220, startedAt: "2025-11-18T07:00:00Z", completedAt: "2025-11-18T10:40:00Z", operatorName: "Anna Berger", notes: "", isParallel: false, isOptional: false },
      { id: "ps-007-3", name: "Cutting", sequence: 3, status: "completed", assignedStation: "Polar 115", estimatedDuration: 90, actualDuration: 85, startedAt: "2025-11-18T13:00:00Z", completedAt: "2025-11-18T14:25:00Z", operatorName: "Erik Hahn", notes: "", isParallel: false, isOptional: false },
      { id: "ps-007-4", name: "QC", sequence: 4, status: "completed", assignedStation: "QC Station", estimatedDuration: 30, actualDuration: 25, startedAt: "2025-11-18T14:30:00Z", completedAt: "2025-11-18T14:55:00Z", operatorName: "Sabine Lehmann", notes: "Spot check passed.", isParallel: false, isOptional: false },
      { id: "ps-007-5", name: "Packaging", sequence: 5, status: "completed", assignedStation: "Packing Area", estimatedDuration: 60, actualDuration: 50, startedAt: "2025-11-18T15:00:00Z", completedAt: "2025-11-18T15:50:00Z", operatorName: "Lukas Maier", notes: "Shrink-wrapped cartons of 2500.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-11-15T09:00:00Z", changedBy: "Thomas Fischer", changes: "Initial job ticket created" },
    ],
    currentVersion: 1,
    createdAt: "2025-11-15T09:00:00Z",
    dueDate: "2025-12-01T17:00:00Z",
    priority: "normal",
    specialInstructions: "Shrink-wrap cartons.",
    materials: [
      { id: "mr-007-1", materialId: "mat-gloss-170", name: "170gsm Gloss Coated", specification: "SRA3 sheets", quantityNeeded: 3200, unit: "sheets", quantityAllocated: 3200, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.08, totalCost: 256 },
    ],
  },
  {
    id: "JOB-2025-008",
    orderId: "ORD-2025-008",
    orderNumber: "ORD-2025-008",
    customerName: "Summit Media Group",
    product: "Event Programme A5",
    quantity: 5000,
    status: "In Progress",
    workflowTemplateId: "wf-offset",
    steps: [
      { id: "ps-008-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 1", estimatedDuration: 90, actualDuration: 85, startedAt: "2025-11-05T08:00:00Z", completedAt: "2025-11-05T09:25:00Z", operatorName: "Martin Schulz", notes: "48 pages + cover imposed. Variable data for badges set up.", isParallel: false, isOptional: false },
      { id: "ps-008-2", name: "Printing — Programmes", sequence: 2, status: "completed", assignedStation: "Heidelberg XL-106", estimatedDuration: 360, actualDuration: 340, startedAt: "2025-11-20T07:00:00Z", completedAt: "2025-11-20T12:40:00Z", operatorName: "Klaus Bauer", notes: "Interior and covers printed.", isParallel: false, isOptional: false },
      { id: "ps-008-3", name: "Printing — Badges", sequence: 3, status: "completed", assignedStation: "HP Indigo 12000", estimatedDuration: 120, actualDuration: 130, startedAt: "2025-11-21T07:00:00Z", completedAt: "2025-11-21T09:10:00Z", operatorName: "Anna Berger", notes: "Variable data print. 5000 unique names.", isParallel: true, isOptional: false },
      { id: "ps-008-4", name: "Lamination", sequence: 4, status: "completed", assignedStation: "Laminator L-1", estimatedDuration: 60, actualDuration: 55, startedAt: "2025-11-21T10:00:00Z", completedAt: "2025-11-21T10:55:00Z", operatorName: "Petra Vogel", notes: "Gloss lamination on programme covers.", isParallel: false, isOptional: false },
      { id: "ps-008-5", name: "Cutting", sequence: 5, status: "in-progress", assignedStation: "Polar 115", estimatedDuration: 90, startedAt: "2025-11-28T08:00:00Z", operatorName: "Erik Hahn", notes: "Cutting programmes and badges.", isParallel: false, isOptional: false },
      { id: "ps-008-6", name: "Binding", sequence: 6, status: "pending", estimatedDuration: 180, notes: "Saddle stitching for programmes.", isParallel: false, isOptional: false },
      { id: "ps-008-7", name: "QC", sequence: 7, status: "pending", estimatedDuration: 60, notes: "Check variable data on badges.", isParallel: false, isOptional: false },
      { id: "ps-008-8", name: "Packaging", sequence: 8, status: "pending", estimatedDuration: 60, notes: "Palletise for venue delivery.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-11-01T11:00:00Z", changedBy: "Emma Thompson", changes: "Initial job ticket created" },
      { version: 2, changedAt: "2025-11-03T09:00:00Z", changedBy: "Emma Thompson", changes: "Added variable data badge printing step" },
    ],
    currentVersion: 2,
    createdAt: "2025-11-01T11:00:00Z",
    dueDate: "2025-12-10T17:00:00Z",
    priority: "high",
    specialInstructions: "Badges have variable data. Deliver to ExCeL London loading bay.",
    materials: [
      { id: "mr-008-1", materialId: "mat-silk-150", name: "150gsm Silk Coated", specification: "SRA3 sheets", quantityNeeded: 5000, unit: "sheets", quantityAllocated: 5000, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.10, totalCost: 500 },
      { id: "mr-008-2", materialId: "mat-silk-300", name: "300gsm Silk Cover", specification: "SRA3 sheets", quantityNeeded: 700, unit: "sheets", quantityAllocated: 700, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.35, totalCost: 245 },
      { id: "mr-008-3", materialId: "mat-card-350", name: "350gsm Card", specification: "SRA3 sheets", quantityNeeded: 450, unit: "sheets", quantityAllocated: 450, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.40, totalCost: 180 },
    ],
  },
  {
    id: "JOB-2025-009",
    orderId: "ORD-2025-009",
    orderNumber: "ORD-2025-009",
    customerName: "Nova Graphics Srl",
    product: "Posters A1 & A2",
    quantity: 1500,
    status: "In Progress",
    workflowTemplateId: "wf-large-format",
    steps: [
      { id: "ps-009-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 2", estimatedDuration: 45, actualDuration: 40, startedAt: "2025-11-23T08:00:00Z", completedAt: "2025-11-23T08:40:00Z", operatorName: "Martin Schulz", notes: "Colour profiles checked for wide-format output.", isParallel: false, isOptional: false },
      { id: "ps-009-2", name: "Printing", sequence: 2, status: "in-progress", assignedStation: "Canon Arizona 2380", estimatedDuration: 180, startedAt: "2025-11-28T09:00:00Z", operatorName: "Anna Berger", notes: "A1 posters running first.", isParallel: false, isOptional: false },
      { id: "ps-009-3", name: "Cutting", sequence: 3, status: "pending", assignedStation: "Zünd G3 Cutter", estimatedDuration: 60, notes: "Trim to final size.", isParallel: false, isOptional: false },
      { id: "ps-009-4", name: "QC", sequence: 4, status: "pending", estimatedDuration: 30, notes: "Colour accuracy check.", isParallel: false, isOptional: false },
      { id: "ps-009-5", name: "Packaging", sequence: 5, status: "pending", estimatedDuration: 45, notes: "Ship flat — do not roll.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-11-22T11:00:00Z", changedBy: "Emma Thompson", changes: "Initial job ticket created" },
    ],
    currentVersion: 1,
    createdAt: "2025-11-22T11:00:00Z",
    dueDate: "2025-12-20T17:00:00Z",
    priority: "normal",
    specialInstructions: "Ship flat, do not roll. Colour accuracy critical.",
    materials: [
      { id: "mr-009-1", materialId: "mat-silk-200", name: "200gsm Silk Coated", specification: "B1 sheets", quantityNeeded: 1600, unit: "sheets", quantityAllocated: 1600, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.55, totalCost: 880 },
    ],
  },
  {
    id: "JOB-2025-011",
    orderId: "ORD-2025-011",
    orderNumber: "ORD-2025-011",
    customerName: "Acme Corporation",
    product: "Corporate Brochure A4",
    quantity: 1000,
    status: "In Progress",
    workflowTemplateId: "wf-offset",
    steps: [
      { id: "ps-011-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 1", estimatedDuration: 60, actualDuration: 50, startedAt: "2025-11-06T08:00:00Z", completedAt: "2025-11-06T08:50:00Z", operatorName: "Martin Schulz", notes: "24 pages imposed.", isParallel: false, isOptional: false },
      { id: "ps-011-2", name: "Printing", sequence: 2, status: "completed", assignedStation: "Heidelberg XL-106", estimatedDuration: 180, actualDuration: 170, startedAt: "2025-11-25T13:00:00Z", completedAt: "2025-11-25T15:50:00Z", operatorName: "Klaus Bauer", notes: "", isParallel: false, isOptional: false },
      { id: "ps-011-3", name: "Lamination", sequence: 3, status: "in-progress", assignedStation: "Laminator L-1", estimatedDuration: 45, startedAt: "2025-11-28T08:00:00Z", operatorName: "Petra Vogel", notes: "Gloss lamination on covers.", isParallel: false, isOptional: false },
      { id: "ps-011-4", name: "Cutting", sequence: 4, status: "pending", estimatedDuration: 30, notes: "", isParallel: false, isOptional: false },
      { id: "ps-011-5", name: "Binding", sequence: 5, status: "pending", estimatedDuration: 90, notes: "Saddle stitching.", isParallel: false, isOptional: false },
      { id: "ps-011-6", name: "QC", sequence: 6, status: "pending", estimatedDuration: 30, notes: "", isParallel: false, isOptional: false },
      { id: "ps-011-7", name: "Packaging", sequence: 7, status: "pending", estimatedDuration: 30, notes: "", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-11-05T09:00:00Z", changedBy: "Thomas Fischer", changes: "Initial job ticket created" },
    ],
    currentVersion: 1,
    createdAt: "2025-11-05T09:00:00Z",
    dueDate: "2025-12-08T17:00:00Z",
    priority: "normal",
    specialInstructions: "Match brand colours to annual report.",
    materials: [
      { id: "mr-011-1", materialId: "mat-silk-170", name: "170gsm Silk Coated", specification: "SRA3 sheets", quantityNeeded: 1500, unit: "sheets", quantityAllocated: 1500, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.12, totalCost: 180 },
    ],
  },
  {
    id: "JOB-2025-012",
    orderId: "ORD-2025-012",
    orderNumber: "ORD-2025-012",
    customerName: "Luxe Labels SA",
    product: "Wine Labels (Reprint)",
    quantity: 10000,
    status: "In Progress",
    workflowTemplateId: "wf-labels",
    steps: [
      { id: "ps-012-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 1", estimatedDuration: 30, actualDuration: 20, startedAt: "2025-11-19T08:00:00Z", completedAt: "2025-11-19T08:20:00Z", operatorName: "Martin Schulz", notes: "Using existing plates from ORD-2025-005.", isParallel: false, isOptional: false },
      { id: "ps-012-2", name: "Printing", sequence: 2, status: "in-progress", assignedStation: "Heidelberg XL-106", estimatedDuration: 180, startedAt: "2025-11-27T07:00:00Z", operatorName: "Klaus Bauer", notes: "Reprint run.", isParallel: false, isOptional: false },
      { id: "ps-012-3", name: "Foil Stamping", sequence: 3, status: "pending", estimatedDuration: 120, notes: "Same gold foil as original run.", isParallel: false, isOptional: false },
      { id: "ps-012-4", name: "Embossing", sequence: 4, status: "pending", estimatedDuration: 90, notes: "Same dies as original.", isParallel: false, isOptional: false },
      { id: "ps-012-5", name: "Cutting", sequence: 5, status: "pending", estimatedDuration: 60, notes: "", isParallel: false, isOptional: false },
      { id: "ps-012-6", name: "QC", sequence: 6, status: "pending", estimatedDuration: 45, notes: "Compare with retained sample from first run.", isParallel: false, isOptional: false },
      { id: "ps-012-7", name: "Packaging", sequence: 7, status: "pending", estimatedDuration: 30, notes: "76mm cores, 1000 per roll.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-11-18T17:00:00Z", changedBy: "Emma Thompson", changes: "Initial job ticket created — reprint of JOB-2025-005" },
    ],
    currentVersion: 1,
    createdAt: "2025-11-18T17:00:00Z",
    dueDate: "2025-12-18T17:00:00Z",
    priority: "normal",
    specialInstructions: "Exact reprint. Use same dies and colour settings as JOB-2025-005.",
    materials: [
      { id: "mr-012-1", materialId: "mat-label-textured", name: "Textured Self-Adhesive Label Stock", specification: "Rolls, 250mm wide", quantityNeeded: 50, unit: "metres", quantityAllocated: 50, status: "reserved", supplier: "Avery Dennison", unitCost: 3.50, totalCost: 175 },
    ],
  },
  {
    id: "JOB-2025-013",
    orderId: "ORD-2025-013",
    orderNumber: "ORD-2025-013",
    customerName: "PrintCo Ltd",
    product: "Compliment Slips",
    quantity: 20000,
    status: "Completed",
    workflowTemplateId: "wf-digital",
    steps: [
      { id: "ps-013-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 2", estimatedDuration: 15, actualDuration: 10, startedAt: "2025-10-16T08:00:00Z", completedAt: "2025-10-16T08:10:00Z", operatorName: "Martin Schulz", notes: "", isParallel: false, isOptional: false },
      { id: "ps-013-2", name: "Printing", sequence: 2, status: "completed", assignedStation: "Konica Minolta C14000", estimatedDuration: 120, actualDuration: 110, startedAt: "2025-10-17T07:00:00Z", completedAt: "2025-10-17T08:50:00Z", operatorName: "Anna Berger", notes: "", isParallel: false, isOptional: false },
      { id: "ps-013-3", name: "Cutting", sequence: 3, status: "completed", assignedStation: "Polar 115", estimatedDuration: 45, actualDuration: 40, startedAt: "2025-10-17T09:00:00Z", completedAt: "2025-10-17T09:40:00Z", operatorName: "Erik Hahn", notes: "", isParallel: false, isOptional: false },
      { id: "ps-013-4", name: "QC", sequence: 4, status: "completed", assignedStation: "QC Station", estimatedDuration: 15, actualDuration: 10, startedAt: "2025-10-17T10:00:00Z", completedAt: "2025-10-17T10:10:00Z", operatorName: "Sabine Lehmann", notes: "Pass.", isParallel: false, isOptional: false },
      { id: "ps-013-5", name: "Packaging", sequence: 5, status: "completed", assignedStation: "Packing Area", estimatedDuration: 30, actualDuration: 25, startedAt: "2025-10-17T10:15:00Z", completedAt: "2025-10-17T10:40:00Z", operatorName: "Lukas Maier", notes: "", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-10-15T10:00:00Z", changedBy: "Emma Thompson", changes: "Initial job ticket created" },
    ],
    currentVersion: 1,
    createdAt: "2025-10-15T10:00:00Z",
    dueDate: "2025-11-05T17:00:00Z",
    priority: "low",
    specialInstructions: "",
    materials: [
      { id: "mr-013-1", materialId: "mat-uncoated-120", name: "120gsm Uncoated", specification: "SRA3 sheets", quantityNeeded: 1700, unit: "sheets", quantityAllocated: 1700, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.06, totalCost: 102 },
    ],
  },
  {
    id: "JOB-2025-014",
    orderId: "ORD-2025-014",
    orderNumber: "ORD-2025-014",
    customerName: "BrandEx GmbH",
    product: "Die-Cut Stickers",
    quantity: 5000,
    status: "In Progress",
    workflowTemplateId: "wf-digital",
    steps: [
      { id: "ps-014-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 2", estimatedDuration: 45, actualDuration: 50, startedAt: "2025-11-26T08:00:00Z", completedAt: "2025-11-26T08:50:00Z", operatorName: "Martin Schulz", notes: "10 designs ganged. Cut path created.", isParallel: false, isOptional: false },
      { id: "ps-014-2", name: "Printing", sequence: 2, status: "in-progress", assignedStation: "HP Indigo 12000", estimatedDuration: 60, startedAt: "2025-11-28T10:00:00Z", operatorName: "Anna Berger", notes: "Digital print on vinyl.", isParallel: false, isOptional: false },
      { id: "ps-014-3", name: "Cutting", sequence: 3, status: "pending", assignedStation: "Zünd G3 Cutter", estimatedDuration: 90, notes: "Kiss-cut on A4 sheets.", isParallel: false, isOptional: false },
      { id: "ps-014-4", name: "QC", sequence: 4, status: "pending", estimatedDuration: 20, notes: "", isParallel: false, isOptional: false },
      { id: "ps-014-5", name: "Packaging", sequence: 5, status: "pending", estimatedDuration: 20, notes: "Pack by design.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-11-25T11:00:00Z", changedBy: "Thomas Fischer", changes: "Initial job ticket created" },
    ],
    currentVersion: 1,
    createdAt: "2025-11-25T11:00:00Z",
    dueDate: "2025-12-12T17:00:00Z",
    priority: "normal",
    specialInstructions: "10 designs, 500 each. Supply on A4 sheets, kiss-cut.",
    materials: [
      { id: "mr-014-1", materialId: "mat-vinyl-sa", name: "Vinyl Self-Adhesive", specification: "SRA3 sheets, gloss white", quantityNeeded: 600, unit: "sheets", quantityAllocated: 600, status: "reserved", supplier: "Avery Dennison", unitCost: 0.85, totalCost: 510 },
    ],
  },
  {
    id: "JOB-2025-015",
    orderId: "ORD-2025-017",
    orderNumber: "ORD-2025-017",
    customerName: "Titan Press OY",
    product: "Business Cards",
    quantity: 5000,
    status: "Completed",
    workflowTemplateId: "wf-digital",
    steps: [
      { id: "ps-015-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 2", estimatedDuration: 20, actualDuration: 15, startedAt: "2025-10-26T08:00:00Z", completedAt: "2025-10-26T08:15:00Z", operatorName: "Martin Schulz", notes: "", isParallel: false, isOptional: false },
      { id: "ps-015-2", name: "Printing", sequence: 2, status: "completed", assignedStation: "Konica Minolta C14000", estimatedDuration: 45, actualDuration: 40, startedAt: "2025-10-27T07:00:00Z", completedAt: "2025-10-27T07:40:00Z", operatorName: "Anna Berger", notes: "", isParallel: false, isOptional: false },
      { id: "ps-015-3", name: "Cutting", sequence: 3, status: "completed", assignedStation: "Polar 115", estimatedDuration: 30, actualDuration: 25, startedAt: "2025-10-27T08:00:00Z", completedAt: "2025-10-27T08:25:00Z", operatorName: "Erik Hahn", notes: "Round corners applied.", isParallel: false, isOptional: false },
      { id: "ps-015-4", name: "QC", sequence: 4, status: "completed", assignedStation: "QC Station", estimatedDuration: 15, actualDuration: 10, startedAt: "2025-10-27T08:30:00Z", completedAt: "2025-10-27T08:40:00Z", operatorName: "Sabine Lehmann", notes: "Pass.", isParallel: false, isOptional: false },
      { id: "ps-015-5", name: "Packaging", sequence: 5, status: "completed", assignedStation: "Packing Area", estimatedDuration: 20, actualDuration: 15, startedAt: "2025-10-27T09:00:00Z", completedAt: "2025-10-27T09:15:00Z", operatorName: "Lukas Maier", notes: "Boxes of 250.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-10-25T11:00:00Z", changedBy: "Emma Thompson", changes: "Initial job ticket created" },
    ],
    currentVersion: 1,
    createdAt: "2025-10-25T11:00:00Z",
    dueDate: "2025-11-15T17:00:00Z",
    priority: "low",
    specialInstructions: "Round corners. Pack in boxes of 250.",
    materials: [
      { id: "mr-015-1", materialId: "mat-uncoated-350", name: "350gsm Uncoated Card", specification: "SRA3 sheets", quantityNeeded: 450, unit: "sheets", quantityAllocated: 450, status: "reserved", supplier: "Papyrus GmbH", unitCost: 0.38, totalCost: 171 },
    ],
  },
  {
    id: "JOB-2025-016",
    orderId: "ORD-2025-004",
    orderNumber: "ORD-2025-004",
    customerName: "Creative Signs NV",
    product: "Exhibition Banners & Display",
    quantity: 14,
    status: "Created",
    workflowTemplateId: "wf-large-format",
    steps: [
      { id: "ps-016-1", name: "Prepress", sequence: 1, status: "pending", estimatedDuration: 60, notes: "Prepare files for large-format output.", isParallel: false, isOptional: false },
      { id: "ps-016-2", name: "Printing — Banners", sequence: 2, status: "pending", estimatedDuration: 120, notes: "440gsm PVC, solvent ink.", isParallel: false, isOptional: false },
      { id: "ps-016-3", name: "Printing — Fabric", sequence: 3, status: "pending", estimatedDuration: 90, notes: "Dye sublimation on polyester.", isParallel: true, isOptional: false },
      { id: "ps-016-4", name: "Cutting", sequence: 4, status: "pending", estimatedDuration: 45, notes: "", isParallel: false, isOptional: false },
      { id: "ps-016-5", name: "Assembly", sequence: 5, status: "pending", estimatedDuration: 90, notes: "Assemble roll-up mechanisms and fabric frames.", isParallel: false, isOptional: false },
      { id: "ps-016-6", name: "QC", sequence: 6, status: "pending", estimatedDuration: 30, notes: "Check fire-retardant cert.", isParallel: false, isOptional: false },
      { id: "ps-016-7", name: "Packaging", sequence: 7, status: "pending", estimatedDuration: 30, notes: "Individual carry cases.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-11-20T12:00:00Z", changedBy: "Thomas Fischer", changes: "Initial job ticket created" },
    ],
    currentVersion: 1,
    createdAt: "2025-11-20T12:00:00Z",
    dueDate: "2026-01-10T17:00:00Z",
    priority: "normal",
    specialInstructions: "Fire-retardant certification required. Deliver to Brussels Expo stand B42.",
    materials: [
      { id: "mr-016-1", materialId: "mat-pvc-440", name: "440gsm PVC Banner Material", specification: "Rolls, 850mm wide", quantityNeeded: 30, unit: "metres", quantityAllocated: 0, status: "ordered", supplier: "SignSupply BV", unitCost: 4.20, totalCost: 126 },
      { id: "mr-016-2", materialId: "mat-polyester-fabric", name: "Polyester Display Fabric", specification: "Rolls, 3200mm wide", quantityNeeded: 12, unit: "metres", quantityAllocated: 0, status: "ordered", supplier: "SignSupply BV", unitCost: 8.50, totalCost: 102 },
    ],
  },
  {
    id: "JOB-2025-017",
    orderId: "ORD-2025-006",
    orderNumber: "ORD-2025-006",
    customerName: "Apex Packaging AG",
    product: "Rigid Gift Box",
    quantity: 3000,
    status: "On Hold",
    workflowTemplateId: "wf-packaging",
    steps: [
      { id: "ps-017-1", name: "Prepress", sequence: 1, status: "completed", assignedStation: "Prepress Desk 1", estimatedDuration: 120, actualDuration: 130, startedAt: "2025-11-29T08:00:00Z", completedAt: "2025-11-29T10:10:00Z", operatorName: "Martin Schulz", notes: "Box template and die lines prepared.", isParallel: false, isOptional: false },
      { id: "ps-017-2", name: "Printing", sequence: 2, status: "pending", estimatedDuration: 240, notes: "CMYK print on wrap paper.", isParallel: false, isOptional: false },
      { id: "ps-017-3", name: "Spot UV", sequence: 3, status: "pending", estimatedDuration: 120, notes: "Outsourced.", isParallel: false, isOptional: false, vendorId: "vendor-finishpro" },
      { id: "ps-017-4", name: "Die Cutting", sequence: 4, status: "pending", estimatedDuration: 180, notes: "New die required.", isParallel: false, isOptional: false },
      { id: "ps-017-5", name: "Box Assembly", sequence: 5, status: "pending", estimatedDuration: 480, notes: "Hand assembly with magnetic closures.", isParallel: false, isOptional: false },
      { id: "ps-017-6", name: "Insert Placement", sequence: 6, status: "pending", estimatedDuration: 240, notes: "EVA foam inserts.", isParallel: false, isOptional: false },
      { id: "ps-017-7", name: "QC", sequence: 7, status: "pending", estimatedDuration: 120, notes: "Full inspection — luxury product.", isParallel: false, isOptional: false },
      { id: "ps-017-8", name: "Packaging", sequence: 8, status: "pending", estimatedDuration: 90, notes: "Individual poly bags, then cartons of 20.", isParallel: false, isOptional: false },
    ],
    versions: [
      { version: 1, changedAt: "2025-11-28T10:00:00Z", changedBy: "Thomas Fischer", changes: "Initial job ticket created" },
      { version: 2, changedAt: "2025-11-29T11:00:00Z", changedBy: "Thomas Fischer", changes: "Put on hold — awaiting client sample approval" },
    ],
    currentVersion: 2,
    createdAt: "2025-11-28T10:00:00Z",
    dueDate: "2026-01-15T17:00:00Z",
    priority: "high",
    specialInstructions: "On hold — awaiting client sample approval before proceeding to print.",
    materials: [
      { id: "mr-017-1", materialId: "mat-art-150", name: "150gsm Art Paper", specification: "SRA2 sheets", quantityNeeded: 4000, unit: "sheets", quantityAllocated: 0, status: "available", supplier: "Papyrus GmbH", unitCost: 0.15, totalCost: 600 },
      { id: "mr-017-2", materialId: "mat-greyboard-2mm", name: "2mm Greyboard", specification: "B1 sheets", quantityNeeded: 1800, unit: "sheets", quantityAllocated: 0, status: "available", supplier: "Papyrus GmbH", unitCost: 0.95, totalCost: 1710 },
    ],
  },
]
