// @ts-nocheck
import type { Order } from "@/lib/types"

export const mockOrders: Order[] = [
  {
    id: "ORD-2025-001",
    customerOrderId: "ACME-PO-4521",
    customerId: "acme-corp",
    customerName: "Acme Corporation",
    estimateId: "EST-2025-001",
    type: "job-based",
    status: "Completed",
    createdAt: "2025-09-05T10:00:00Z",
    dueDate: "2025-09-25T17:00:00Z",
    destination: "Germany",
    destinationFlag: "🇩🇪",
    addresses: [
      { id: "addr-001-1", label: "Munich HQ", name: "Hans Weber", company: "Acme Corporation", street: "Industriestraße 42", city: "München", state: "Bavaria", postalCode: "80331", country: "Germany", countryFlag: "🇩🇪", quantity: 1500 },
      { id: "addr-001-2", label: "London Office", name: "Emily Watson", company: "Acme Corporation UK", street: "10 Downing Rd", city: "London", state: "", postalCode: "EC2A 1NT", country: "United Kingdom", countryFlag: "🇬🇧", quantity: 500 },
    ],
    lineItems: [
      { id: "oli-001-1", product: "Annual Report A4", description: "64-page perfect-bound, 170gsm silk interior, 350gsm silk cover with matt lamination", quantity: 2000, unitPrice: 4.85, total: 9700, specs: { pages: "64", binding: "Perfect Bound", paperInterior: "170gsm Silk", paperCover: "350gsm Silk", finish: "Matt Lamination" } },
      { id: "oli-001-2", product: "Executive Summary A5", description: "16-page saddle-stitched, 200gsm gloss throughout", quantity: 500, unitPrice: 1.60, total: 800, specs: { pages: "16", binding: "Saddle Stitched", paper: "200gsm Gloss" } },
    ],
    subtotal: 10500,
    customCosts: [
      { id: "cc-001-1", description: "Express courier to London", amount: 185, type: "shipping", addedBy: "Thomas Fischer", addedAt: "2025-09-06T09:00:00Z" },
    ],
    tax: 2030.10,
    total: 12715.10,
    specialInstructions: "FSC-certified stock required. Pack Munich delivery on Euro pallets.",
    editHistory: [],
    jobTicketId: "JOB-2025-001",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [
      { id: "ne-001-1", trigger: "order_confirmed", sentAt: "2025-09-05T10:15:00Z", recipientEmail: "h.weber@acme-corp.de", recipientName: "Hans Weber", subject: "Order ORD-2025-001 Confirmed", status: "delivered" },
      { id: "ne-001-2", trigger: "shipped", sentAt: "2025-09-22T14:00:00Z", recipientEmail: "h.weber@acme-corp.de", recipientName: "Hans Weber", subject: "Your order has shipped", status: "delivered" },
    ],
  },
  {
    id: "ORD-2025-002",
    customerOrderId: "PC-2025-0892",
    customerId: "printco-ltd",
    customerName: "PrintCo Ltd",
    type: "manual",
    status: "In Production",
    createdAt: "2025-11-10T09:30:00Z",
    dueDate: "2025-12-05T17:00:00Z",
    destination: "United Kingdom",
    destinationFlag: "🇬🇧",
    addresses: [
      { id: "addr-002-1", label: "Warehouse", name: "James Clarke", company: "PrintCo Ltd", street: "Unit 7, Park Royal Industrial Estate", city: "London", state: "", postalCode: "NW10 7LQ", country: "United Kingdom", countryFlag: "🇬🇧", quantity: 50000 },
    ],
    lineItems: [
      { id: "oli-002-1", product: "Business Cards", description: "85x55mm, 400gsm silk, double-sided CMYK, matt lamination", quantity: 50000, unitPrice: 0.055, total: 2750, specs: { size: "85x55mm", paper: "400gsm Silk", sides: "Double", finish: "Matt Lamination" } },
    ],
    subtotal: 2750,
    customCosts: [],
    tax: 550,
    total: 3300,
    specialInstructions: "Pack in boxes of 250. Each box labelled with customer name.",
    editHistory: [],
    jobTicketId: "JOB-2025-002",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [
      { id: "ne-002-1", trigger: "order_confirmed", sentAt: "2025-11-10T09:45:00Z", recipientEmail: "j.clarke@printco.co.uk", recipientName: "James Clarke", subject: "Order ORD-2025-002 Confirmed", status: "delivered" },
    ],
  },
  {
    id: "ORD-2025-003",
    customerOrderId: "BX-CAT-2026S",
    customerId: "brandex",
    customerName: "BrandEx GmbH",
    estimateId: "EST-2025-002",
    type: "job-based",
    status: "In Production",
    createdAt: "2025-10-01T14:00:00Z",
    dueDate: "2025-12-15T17:00:00Z",
    destination: "Austria",
    destinationFlag: "🇦🇹",
    addresses: [
      { id: "addr-003-1", label: "Vienna Office", name: "Anna Hofmann", company: "BrandEx GmbH", street: "Kärntner Straße 18", city: "Wien", state: "", postalCode: "1010", country: "Austria", countryFlag: "🇦🇹", quantity: 3000 },
      { id: "addr-003-2", label: "Salzburg Warehouse", name: "Markus Steiner", company: "BrandEx GmbH", street: "Gewerbepark 5", city: "Salzburg", state: "", postalCode: "5020", country: "Austria", countryFlag: "🇦🇹", quantity: 2000 },
    ],
    lineItems: [
      { id: "oli-003-1", product: "Product Catalogue A4", description: "96-page perfect-bound, 150gsm silk interior, 300gsm art cover with spot UV", quantity: 5000, unitPrice: 3.20, total: 16000, specs: { pages: "96", binding: "Perfect Bound", paperInterior: "150gsm Silk", paperCover: "300gsm Art", finish: "Spot UV" } },
    ],
    subtotal: 16000,
    customCosts: [
      { id: "cc-003-1", description: "Pantone 186C spot colour", amount: 450, type: "material", addedBy: "Thomas Fischer", addedAt: "2025-10-02T09:00:00Z" },
    ],
    tax: 3290,
    total: 19740,
    specialInstructions: "Pantone 186C must be spot colour, not simulated. Proof approval required before production.",
    editHistory: [],
    jobTicketId: "JOB-2025-003",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-004",
    customerOrderId: "CS-EXPO-2026",
    customerId: "creative-signs",
    customerName: "Creative Signs NV",
    type: "job-based",
    status: "Pending",
    createdAt: "2025-11-20T11:00:00Z",
    dueDate: "2026-01-10T17:00:00Z",
    destination: "Belgium",
    destinationFlag: "🇧🇪",
    addresses: [
      { id: "addr-004-1", label: "Brussels Expo", name: "Pierre Dubois", company: "Creative Signs NV", street: "Place de Belgique 1", city: "Bruxelles", state: "", postalCode: "1020", country: "Belgium", countryFlag: "🇧🇪", quantity: 14 },
    ],
    lineItems: [
      { id: "oli-004-1", product: "Roll-Up Banner", description: "850x2000mm, 440gsm PVC banner, full-colour single-sided", quantity: 12, unitPrice: 65.00, total: 780, specs: { size: "850x2000mm", material: "440gsm PVC", sides: "Single" } },
      { id: "oli-004-2", product: "Fabric Display Wall", description: "3000x2400mm, polyester fabric, double-sided sublimation", quantity: 2, unitPrice: 320.00, total: 640, specs: { size: "3000x2400mm", material: "Polyester Fabric", sides: "Double", printMethod: "Sublimation" } },
    ],
    subtotal: 1420,
    customCosts: [],
    tax: 298.20,
    total: 1718.20,
    specialInstructions: "Fire-retardant certification needed for trade fair. Deliver directly to stand B42.",
    editHistory: [],
    proofStatus: "pending",
    fileStatus: "uploaded",
    notificationLog: [],
  },
  {
    id: "ORD-2025-005",
    customerOrderId: "LL-WINE-2022V",
    customerId: "luxe-labels",
    customerName: "Luxe Labels SA",
    estimateId: "EST-2025-005",
    type: "job-based",
    status: "Shipped",
    createdAt: "2025-08-25T10:00:00Z",
    dueDate: "2025-09-30T17:00:00Z",
    destination: "France",
    destinationFlag: "🇫🇷",
    addresses: [
      { id: "addr-005-1", label: "Château Margaux", name: "Camille Laurent", company: "Luxe Labels SA", street: "Route du Château", city: "Margaux-Cantenac", state: "Gironde", postalCode: "33460", country: "France", countryFlag: "🇫🇷", quantity: 25000 },
    ],
    lineItems: [
      { id: "oli-005-1", product: "Wine Front Label", description: "90x120mm, self-adhesive textured stock, gold foil stamping + emboss", quantity: 25000, unitPrice: 0.18, total: 4500, specs: { size: "90x120mm", material: "Textured Self-Adhesive", finish: "Gold Foil + Emboss" } },
      { id: "oli-005-2", product: "Wine Back Label", description: "70x100mm, self-adhesive textured stock, CMYK", quantity: 25000, unitPrice: 0.08, total: 2000, specs: { size: "70x100mm", material: "Textured Self-Adhesive", finish: "None" } },
    ],
    subtotal: 6500,
    customCosts: [
      { id: "cc-005-1", description: "Gold foil die charge", amount: 380, type: "material", addedBy: "Emma Thompson", addedAt: "2025-08-26T10:00:00Z" },
      { id: "cc-005-2", description: "Embossing die charge", amount: 290, type: "material", addedBy: "Emma Thompson", addedAt: "2025-08-26T10:05:00Z" },
    ],
    tax: 1434,
    total: 8604,
    specialInstructions: "Colour must match 2021 vintage labels exactly. Press proof required. Labels must be wound on 76mm cores, 1000 per roll.",
    editHistory: [],
    jobTicketId: "JOB-2025-005",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [
      { id: "ne-005-1", trigger: "shipped", sentAt: "2025-09-25T09:00:00Z", recipientEmail: "c.laurent@luxe-labels.fr", recipientName: "Camille Laurent", subject: "Your labels have shipped", status: "delivered" },
    ],
  },
  {
    id: "ORD-2025-006",
    customerOrderId: "AP-BOX-Q4",
    customerId: "apex-packaging",
    customerName: "Apex Packaging AG",
    type: "job-based",
    status: "Confirmed",
    createdAt: "2025-11-28T09:00:00Z",
    dueDate: "2026-01-15T17:00:00Z",
    destination: "Switzerland",
    destinationFlag: "🇨🇭",
    addresses: [
      { id: "addr-006-1", label: "Zürich Factory", name: "Stefan Keller", company: "Apex Packaging AG", street: "Bahnhofstrasse 50", city: "Zürich", state: "", postalCode: "8001", country: "Switzerland", countryFlag: "🇨🇭", quantity: 3000 },
    ],
    lineItems: [
      { id: "oli-006-1", product: "Rigid Gift Box", description: "200x150x80mm, 2mm greyboard wrapped with 150gsm art paper, CMYK + spot UV, magnetic closure", quantity: 3000, unitPrice: 4.50, total: 13500, specs: { size: "200x150x80mm", material: "2mm Greyboard + 150gsm Art", finish: "Spot UV", closure: "Magnetic" } },
      { id: "oli-006-2", product: "Insert Tray", description: "EVA foam insert, custom die-cut", quantity: 3000, unitPrice: 1.80, total: 5400, specs: { material: "EVA Foam", type: "Custom Die-Cut" } },
    ],
    subtotal: 18900,
    customCosts: [
      { id: "cc-006-1", description: "Die-cut tooling charge", amount: 750, type: "material", addedBy: "Thomas Fischer", addedAt: "2025-11-28T10:00:00Z" },
    ],
    tax: 3930,
    total: 23580,
    specialInstructions: "FSC-certified stock. Samples required before bulk run. Include QC report with delivery.",
    editHistory: [],
    proofStatus: "sent",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-007",
    customerOrderId: "MP-FLY-DEC",
    customerId: "metro-print",
    customerName: "Metro Print Services",
    type: "manual",
    status: "Ready to Ship",
    createdAt: "2025-11-15T08:00:00Z",
    dueDate: "2025-12-01T17:00:00Z",
    destination: "Netherlands",
    destinationFlag: "🇳🇱",
    addresses: [
      { id: "addr-007-1", label: "Amsterdam Office", name: "Jan de Vries", company: "Metro Print Services", street: "Herengracht 200", city: "Amsterdam", state: "", postalCode: "1016 BS", country: "Netherlands", countryFlag: "🇳🇱", quantity: 25000 },
    ],
    lineItems: [
      { id: "oli-007-1", product: "DL Flyers", description: "99x210mm, 170gsm gloss, double-sided CMYK", quantity: 25000, unitPrice: 0.028, total: 700, specs: { size: "99x210mm", paper: "170gsm Gloss", sides: "Double" } },
      { id: "oli-007-2", product: "A5 Flyers", description: "148x210mm, 170gsm gloss, double-sided CMYK", quantity: 10000, unitPrice: 0.045, total: 450, specs: { size: "148x210mm", paper: "170gsm Gloss", sides: "Double" } },
    ],
    subtotal: 1150,
    customCosts: [],
    tax: 241.50,
    total: 1391.50,
    specialInstructions: "Pack in cartons of 2500. Shrink-wrap each carton.",
    editHistory: [],
    jobTicketId: "JOB-2025-007",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-008",
    customerOrderId: "SM-PROG-2026",
    customerId: "summit-media",
    customerName: "Summit Media Group",
    type: "job-based",
    status: "Printed",
    createdAt: "2025-11-01T10:00:00Z",
    dueDate: "2025-12-10T17:00:00Z",
    destination: "United Kingdom",
    destinationFlag: "🇬🇧",
    addresses: [
      { id: "addr-008-1", label: "Event Venue", name: "Oliver Grant", company: "Summit Media Group", street: "ExCeL London, Royal Victoria Dock", city: "London", state: "", postalCode: "E16 1XL", country: "United Kingdom", countryFlag: "🇬🇧", quantity: 5000 },
    ],
    lineItems: [
      { id: "oli-008-1", product: "Event Programme A5", description: "48-page saddle-stitched, 150gsm silk interior, 300gsm silk cover with gloss lamination", quantity: 5000, unitPrice: 1.75, total: 8750, specs: { pages: "48", binding: "Saddle Stitched", paperInterior: "150gsm Silk", paperCover: "300gsm Silk", finish: "Gloss Lamination" } },
      { id: "oli-008-2", product: "Delegate Badge", description: "A6, 350gsm card, single-sided digital print with lanyard hole", quantity: 5000, unitPrice: 0.35, total: 1750, specs: { size: "A6", paper: "350gsm Card", sides: "Single", finish: "Lanyard Hole Punch" } },
    ],
    subtotal: 10500,
    customCosts: [
      { id: "cc-008-1", description: "Variable data setup for badges", amount: 250, type: "labor", addedBy: "Emma Thompson", addedAt: "2025-11-02T09:00:00Z" },
    ],
    tax: 2150,
    total: 12900,
    specialInstructions: "Badges have variable data (delegate names). Data file to follow. Deliver to venue loading bay.",
    editHistory: [],
    jobTicketId: "JOB-2025-008",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-009",
    customerOrderId: "NG-POST-GAL",
    customerId: "nova-graphics",
    customerName: "Nova Graphics Srl",
    type: "manual",
    status: "In Production",
    createdAt: "2025-11-22T10:00:00Z",
    dueDate: "2025-12-20T17:00:00Z",
    destination: "Italy",
    destinationFlag: "🇮🇹",
    addresses: [
      { id: "addr-009-1", label: "Gallery", name: "Marco Rossi", company: "Nova Graphics Srl", street: "Via della Conciliazione 10", city: "Roma", state: "Lazio", postalCode: "00193", country: "Italy", countryFlag: "🇮🇹", quantity: 1500 },
    ],
    lineItems: [
      { id: "oli-009-1", product: "Poster A1", description: "594x841mm, 200gsm silk, single-sided CMYK", quantity: 500, unitPrice: 1.90, total: 950, specs: { size: "A1 (594x841mm)", paper: "200gsm Silk", sides: "Single" } },
      { id: "oli-009-2", product: "Poster A2", description: "420x594mm, 200gsm silk, single-sided CMYK", quantity: 1000, unitPrice: 0.95, total: 950, specs: { size: "A2 (420x594mm)", paper: "200gsm Silk", sides: "Single" } },
    ],
    subtotal: 1900,
    customCosts: [],
    tax: 418,
    total: 2318,
    specialInstructions: "Gallery exhibition prints — colour accuracy critical. Ship flat, do not roll.",
    editHistory: [],
    jobTicketId: "JOB-2025-009",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-010",
    customerOrderId: "TP-BRO-NORDIC",
    customerId: "titan-press",
    customerName: "Titan Press OY",
    type: "job-based",
    status: "Confirmed",
    createdAt: "2025-11-15T14:00:00Z",
    dueDate: "2025-12-20T17:00:00Z",
    destination: "Finland",
    destinationFlag: "🇫🇮",
    addresses: [
      { id: "addr-010-1", label: "Helsinki Warehouse", name: "Mika Virtanen", company: "Titan Press OY", street: "Mannerheimintie 15", city: "Helsinki", state: "", postalCode: "00100", country: "Finland", countryFlag: "🇫🇮", quantity: 10000 },
    ],
    lineItems: [
      { id: "oli-010-1", product: "Tri-Fold Brochure", description: "A4 folding to DL, 200gsm silk, double-sided CMYK, 2 x fold", quantity: 10000, unitPrice: 0.18, total: 1800, specs: { size: "A4 to DL", paper: "200gsm Silk", sides: "Double", folds: "2 (Tri-Fold)" } },
    ],
    subtotal: 1800,
    customCosts: [],
    tax: 360,
    total: 2160,
    specialInstructions: "English version. Finnish version order to follow. Palletise for freight.",
    editHistory: [],
    proofStatus: "pending",
    fileStatus: "uploaded",
    notificationLog: [],
  },
  {
    id: "ORD-2025-011",
    customerOrderId: "ACME-PO-4580",
    customerId: "acme-corp",
    customerName: "Acme Corporation",
    type: "job-based",
    status: "Finishing",
    createdAt: "2025-11-05T08:00:00Z",
    dueDate: "2025-12-08T17:00:00Z",
    destination: "Germany",
    destinationFlag: "🇩🇪",
    addresses: [
      { id: "addr-011-1", label: "Munich HQ", name: "Hans Weber", company: "Acme Corporation", street: "Industriestraße 42", city: "München", state: "Bavaria", postalCode: "80331", country: "Germany", countryFlag: "🇩🇪", quantity: 1000 },
    ],
    lineItems: [
      { id: "oli-011-1", product: "Corporate Brochure A4", description: "24-page saddle-stitched, 170gsm silk throughout, gloss lamination on cover", quantity: 1000, unitPrice: 2.10, total: 2100, specs: { pages: "24", binding: "Saddle Stitched", paper: "170gsm Silk", finish: "Gloss Lamination Cover" } },
    ],
    subtotal: 2100,
    customCosts: [],
    tax: 399,
    total: 2499,
    specialInstructions: "Use same brand colours as annual report. Artwork provided.",
    editHistory: [],
    jobTicketId: "JOB-2025-011",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-012",
    customerOrderId: "LL-WINE-RPT",
    customerId: "luxe-labels",
    customerName: "Luxe Labels SA",
    type: "reprint",
    status: "In Production",
    createdAt: "2025-11-18T16:00:00Z",
    dueDate: "2025-12-18T17:00:00Z",
    destination: "France",
    destinationFlag: "🇫🇷",
    reprintOfOrderId: "ORD-2025-005",
    reprintReason: "Additional stock needed for Christmas season",
    addresses: [
      { id: "addr-012-1", label: "Château Margaux", name: "Camille Laurent", company: "Luxe Labels SA", street: "Route du Château", city: "Margaux-Cantenac", state: "Gironde", postalCode: "33460", country: "France", countryFlag: "🇫🇷", quantity: 10000 },
    ],
    lineItems: [
      { id: "oli-012-1", product: "Wine Front Label", description: "90x120mm, self-adhesive textured stock, gold foil stamping + emboss", quantity: 10000, unitPrice: 0.20, total: 2000, specs: { size: "90x120mm", material: "Textured Self-Adhesive", finish: "Gold Foil + Emboss" } },
      { id: "oli-012-2", product: "Wine Back Label", description: "70x100mm, self-adhesive textured stock, CMYK", quantity: 10000, unitPrice: 0.09, total: 900, specs: { size: "70x100mm", material: "Textured Self-Adhesive", finish: "None" } },
    ],
    subtotal: 2900,
    customCosts: [],
    tax: 580,
    total: 3480,
    specialInstructions: "Exact reprint of ORD-2025-005. Use same dies and colour settings.",
    editHistory: [],
    jobTicketId: "JOB-2025-012",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-013",
    customerOrderId: "PC-2025-0915",
    customerId: "printco-ltd",
    customerName: "PrintCo Ltd",
    type: "manual",
    status: "Delivered",
    createdAt: "2025-10-15T09:00:00Z",
    dueDate: "2025-11-05T17:00:00Z",
    destination: "United Kingdom",
    destinationFlag: "🇬🇧",
    addresses: [
      { id: "addr-013-1", label: "Warehouse", name: "James Clarke", company: "PrintCo Ltd", street: "Unit 7, Park Royal Industrial Estate", city: "London", state: "", postalCode: "NW10 7LQ", country: "United Kingdom", countryFlag: "🇬🇧", quantity: 20000 },
    ],
    lineItems: [
      { id: "oli-013-1", product: "Compliment Slips", description: "210x99mm, 120gsm uncoated, single-sided CMYK", quantity: 20000, unitPrice: 0.035, total: 700, specs: { size: "210x99mm", paper: "120gsm Uncoated", sides: "Single" } },
    ],
    subtotal: 700,
    customCosts: [],
    tax: 140,
    total: 840,
    specialInstructions: "Standard packaging.",
    editHistory: [],
    jobTicketId: "JOB-2025-013",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-014",
    customerOrderId: "BX-STICKER-Q4",
    customerId: "brandex",
    customerName: "BrandEx GmbH",
    type: "manual",
    status: "In Production",
    createdAt: "2025-11-25T10:00:00Z",
    dueDate: "2025-12-12T17:00:00Z",
    destination: "Austria",
    destinationFlag: "🇦🇹",
    addresses: [
      { id: "addr-014-1", label: "Vienna Office", name: "Anna Hofmann", company: "BrandEx GmbH", street: "Kärntner Straße 18", city: "Wien", state: "", postalCode: "1010", country: "Austria", countryFlag: "🇦🇹", quantity: 5000 },
    ],
    lineItems: [
      { id: "oli-014-1", product: "Die-Cut Stickers", description: "Various sizes, vinyl self-adhesive, full-colour digital print, kiss-cut on sheets", quantity: 5000, unitPrice: 0.15, total: 750, specs: { material: "Vinyl Self-Adhesive", print: "Digital CMYK", cut: "Kiss-Cut" } },
    ],
    subtotal: 750,
    customCosts: [],
    tax: 150,
    total: 900,
    specialInstructions: "10 different designs, 500 of each. Supply on A4 sheets.",
    editHistory: [],
    jobTicketId: "JOB-2025-014",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-015",
    customerOrderId: "AP-TAG-XMAS",
    customerId: "apex-packaging",
    customerName: "Apex Packaging AG",
    type: "job-based",
    status: "Cancelled",
    createdAt: "2025-10-20T09:00:00Z",
    dueDate: "2025-11-25T17:00:00Z",
    destination: "Switzerland",
    destinationFlag: "🇨🇭",
    addresses: [
      { id: "addr-015-1", label: "Zürich Factory", name: "Stefan Keller", company: "Apex Packaging AG", street: "Bahnhofstrasse 50", city: "Zürich", state: "", postalCode: "8001", country: "Switzerland", countryFlag: "🇨🇭", quantity: 10000 },
    ],
    lineItems: [
      { id: "oli-015-1", product: "Hang Tags", description: "50x80mm, 350gsm silk, double-sided CMYK, hole punch + string", quantity: 10000, unitPrice: 0.12, total: 1200, specs: { size: "50x80mm", paper: "350gsm Silk", finish: "Hole Punch + String" } },
    ],
    subtotal: 1200,
    customCosts: [],
    tax: 240,
    total: 1440,
    specialInstructions: "Cancelled — client postponed product launch.",
    editHistory: [
      { id: "eh-015-1", field: "status", oldValue: "Confirmed", newValue: "Cancelled", editedBy: "Thomas Fischer", editedAt: "2025-10-28T14:00:00Z", reason: "Client requested cancellation — product launch postponed to Q1 2026" },
    ],
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-016",
    customerOrderId: "ACME-PO-4601",
    customerId: "acme-corp",
    customerName: "Acme Corporation",
    type: "reprint",
    status: "Pending",
    createdAt: "2025-11-28T15:00:00Z",
    dueDate: "2025-12-15T17:00:00Z",
    destination: "Germany",
    destinationFlag: "🇩🇪",
    reprintOfOrderId: "ORD-2025-001",
    reprintReason: "Additional copies needed for trade show",
    addresses: [
      { id: "addr-016-1", label: "Munich HQ", name: "Hans Weber", company: "Acme Corporation", street: "Industriestraße 42", city: "München", state: "Bavaria", postalCode: "80331", country: "Germany", countryFlag: "🇩🇪", quantity: 500 },
    ],
    lineItems: [
      { id: "oli-016-1", product: "Annual Report A4", description: "64-page perfect-bound, 170gsm silk interior, 350gsm silk cover with matt lamination", quantity: 500, unitPrice: 5.20, total: 2600, specs: { pages: "64", binding: "Perfect Bound", paperInterior: "170gsm Silk", paperCover: "350gsm Silk", finish: "Matt Lamination" } },
    ],
    subtotal: 2600,
    customCosts: [
      { id: "cc-016-1", description: "Rush surcharge (5 working days)", amount: 520, type: "rush", addedBy: "Thomas Fischer", addedAt: "2025-11-28T15:30:00Z" },
    ],
    tax: 592.80,
    total: 3712.80,
    specialInstructions: "Rush order — reprint of annual report for Hannover Messe. Same specs as ORD-2025-001.",
    editHistory: [],
    proofStatus: "none",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-017",
    customerOrderId: "TP-CARD-CORP",
    customerId: "titan-press",
    customerName: "Titan Press OY",
    type: "manual",
    status: "Shipped",
    createdAt: "2025-10-25T10:00:00Z",
    dueDate: "2025-11-15T17:00:00Z",
    destination: "Finland",
    destinationFlag: "🇫🇮",
    addresses: [
      { id: "addr-017-1", label: "Helsinki Warehouse", name: "Mika Virtanen", company: "Titan Press OY", street: "Mannerheimintie 15", city: "Helsinki", state: "", postalCode: "00100", country: "Finland", countryFlag: "🇫🇮", quantity: 5000 },
    ],
    lineItems: [
      { id: "oli-017-1", product: "Business Cards", description: "85x55mm, 350gsm uncoated, double-sided CMYK, round corners", quantity: 5000, unitPrice: 0.065, total: 325, specs: { size: "85x55mm", paper: "350gsm Uncoated", sides: "Double", finish: "Round Corners" } },
    ],
    subtotal: 325,
    customCosts: [],
    tax: 65,
    total: 390,
    specialInstructions: "Pack in boxes of 250.",
    editHistory: [],
    jobTicketId: "JOB-2025-015",
    proofStatus: "approved",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
  {
    id: "ORD-2025-018",
    customerOrderId: "NG-MENU-REST",
    customerId: "nova-graphics",
    customerName: "Nova Graphics Srl",
    type: "manual",
    status: "Confirmed",
    createdAt: "2025-11-27T14:00:00Z",
    dueDate: "2025-12-18T17:00:00Z",
    destination: "Italy",
    destinationFlag: "🇮🇹",
    addresses: [
      { id: "addr-018-1", label: "Restaurant Group", name: "Marco Rossi", company: "Nova Graphics Srl", street: "Via della Conciliazione 10", city: "Roma", state: "Lazio", postalCode: "00193", country: "Italy", countryFlag: "🇮🇹", quantity: 200 },
    ],
    lineItems: [
      { id: "oli-018-1", product: "Restaurant Menus", description: "A4, 350gsm silk, double-sided CMYK, matt lamination both sides", quantity: 200, unitPrice: 1.80, total: 360, specs: { size: "A4", paper: "350gsm Silk", sides: "Double", finish: "Matt Lamination Both Sides" } },
    ],
    subtotal: 360,
    customCosts: [],
    tax: 79.20,
    total: 439.20,
    specialInstructions: "4 different menu versions, 50 of each.",
    editHistory: [],
    proofStatus: "sent",
    fileStatus: "preflight-pass",
    notificationLog: [],
  },
]
