// @ts-nocheck
import type { Vendor, PurchaseOrder } from "@/lib/types"

export const mockVendors: Vendor[] = [
  {
    id: "vendor-finishpro",
    name: "FinishPro Veredlung GmbH",
    contactName: "Wolfgang Braun",
    email: "w.braun@finishpro.de",
    phone: "+49 89 555 1234",
    address: "Gewerbegebiet Ost 12, 85748 Garching, Germany",
    capabilities: [
      { service: "Spot UV Coating", description: "Selective UV varnish application, min 200gsm stock", leadTimeDays: 3, minOrderValue: 200 },
      { service: "Foil Stamping", description: "Hot foil stamping — gold, silver, copper, custom colours", leadTimeDays: 4, minOrderValue: 300 },
      { service: "Embossing / Debossing", description: "Blind and registered embossing, custom dies", leadTimeDays: 5, minOrderValue: 250 },
    ],
    rateCards: [
      { id: "rc-fp-1", service: "Spot UV", unit: "sheet", tiers: [{ minQty: 100, maxQty: 500, rate: 0.35 }, { minQty: 501, maxQty: 2000, rate: 0.25 }, { minQty: 2001, maxQty: 10000, rate: 0.18 }] },
      { id: "rc-fp-2", service: "Foil Stamping", unit: "impression", tiers: [{ minQty: 500, maxQty: 5000, rate: 0.12 }, { minQty: 5001, maxQty: 25000, rate: 0.08 }, { minQty: 25001, maxQty: 100000, rate: 0.05 }] },
    ],
    onTimePercentage: 94,
    qualityRating: 4.7,
    avgLeadTimeDays: 4,
    totalOrders: 128,
    status: "Active",
  },
  {
    id: "vendor-bindwell",
    name: "Bindwell Buchbinderei AG",
    contactName: "Heidi Zimmermann",
    email: "h.zimmermann@bindwell.ch",
    phone: "+41 44 333 5678",
    address: "Industrieweg 8, 8604 Volketswil, Switzerland",
    capabilities: [
      { service: "Perfect Binding", description: "PUR and EVA perfect binding, up to 400pp", leadTimeDays: 3, minOrderValue: 500 },
      { service: "Case Binding", description: "Hardcover case binding with dust jackets", leadTimeDays: 7, minOrderValue: 1000 },
      { service: "Wire-O Binding", description: "Twin-loop wire binding, various sizes", leadTimeDays: 2, minOrderValue: 150 },
    ],
    rateCards: [
      { id: "rc-bw-1", service: "Perfect Binding", unit: "book", tiers: [{ minQty: 100, maxQty: 500, rate: 1.20 }, { minQty: 501, maxQty: 2000, rate: 0.85 }, { minQty: 2001, maxQty: 10000, rate: 0.55 }] },
      { id: "rc-bw-2", service: "Case Binding", unit: "book", tiers: [{ minQty: 50, maxQty: 500, rate: 4.50 }, { minQty: 501, maxQty: 2000, rate: 3.20 }, { minQty: 2001, maxQty: 5000, rate: 2.50 }] },
    ],
    onTimePercentage: 97,
    qualityRating: 4.9,
    avgLeadTimeDays: 4,
    totalOrders: 85,
    status: "Active",
  },
  {
    id: "vendor-scandia-die",
    name: "Scandia Die-Cutting ApS",
    contactName: "Lars Andersen",
    email: "l.andersen@scandia-die.dk",
    phone: "+45 33 12 3456",
    address: "Vesterbrogade 55, 1620 København, Denmark",
    capabilities: [
      { service: "Die Cutting", description: "Flatbed and rotary die cutting, custom dies manufactured in-house", leadTimeDays: 5, minOrderValue: 400 },
      { service: "Creasing & Scoring", description: "Precision creasing for folding cartons", leadTimeDays: 2, minOrderValue: 200 },
    ],
    rateCards: [
      { id: "rc-sd-1", service: "Die Cutting", unit: "sheet", tiers: [{ minQty: 500, maxQty: 2000, rate: 0.18 }, { minQty: 2001, maxQty: 10000, rate: 0.12 }, { minQty: 10001, maxQty: 50000, rate: 0.08 }] },
    ],
    onTimePercentage: 91,
    qualityRating: 4.5,
    avgLeadTimeDays: 5,
    totalOrders: 42,
    status: "Active",
  },
  {
    id: "vendor-colourcraft",
    name: "ColourCraft Digital Ltd",
    contactName: "Rebecca Hughes",
    email: "r.hughes@colourcraft.co.uk",
    phone: "+44 20 7123 4567",
    address: "Unit 3, Meridian Business Park, London SE10 0PE, UK",
    capabilities: [
      { service: "Large Format Printing", description: "UV flatbed and roll-to-roll, up to 3.2m wide", leadTimeDays: 3, minOrderValue: 100 },
      { service: "Dye Sublimation", description: "Fabric printing via dye sublimation transfer", leadTimeDays: 4, minOrderValue: 150 },
    ],
    rateCards: [
      { id: "rc-cc-1", service: "Large Format UV", unit: "sqm", tiers: [{ minQty: 1, maxQty: 10, rate: 28.00 }, { minQty: 11, maxQty: 50, rate: 22.00 }, { minQty: 51, maxQty: 200, rate: 18.00 }] },
      { id: "rc-cc-2", service: "Dye Sublimation", unit: "sqm", tiers: [{ minQty: 1, maxQty: 10, rate: 35.00 }, { minQty: 11, maxQty: 50, rate: 28.00 }, { minQty: 51, maxQty: 200, rate: 22.00 }] },
    ],
    onTimePercentage: 88,
    qualityRating: 4.3,
    avgLeadTimeDays: 4,
    totalOrders: 31,
    status: "Active",
  },
  {
    id: "vendor-packform",
    name: "PackForm Solutions Srl",
    contactName: "Giovanni Russo",
    email: "g.russo@packform.it",
    phone: "+39 02 8765 4321",
    address: "Via dell'Industria 22, 20090 Assago MI, Italy",
    capabilities: [
      { service: "Box Assembly", description: "Rigid box assembly, magnetic closures, ribbon pulls", leadTimeDays: 7, minOrderValue: 2000 },
      { service: "Foam Inserts", description: "CNC-cut EVA and PE foam inserts", leadTimeDays: 5, minOrderValue: 500 },
    ],
    rateCards: [
      { id: "rc-pf-1", service: "Rigid Box Assembly", unit: "box", tiers: [{ minQty: 100, maxQty: 500, rate: 3.80 }, { minQty: 501, maxQty: 2000, rate: 2.90 }, { minQty: 2001, maxQty: 10000, rate: 2.20 }] },
    ],
    onTimePercentage: 85,
    qualityRating: 4.4,
    avgLeadTimeDays: 6,
    totalOrders: 18,
    status: "Pending",
  },
]

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: "VPO-2025-001",
    vendorId: "vendor-finishpro",
    vendorName: "FinishPro Veredlung GmbH",
    orderId: "ORD-2025-003",
    orderNumber: "ORD-2025-003",
    jobTicketId: "JOB-2025-003",
    stepName: "Spot UV",
    specs: { type: "Selective UV varnish", coverage: "Logo and key visuals on cover", stock: "300gsm Art Board" },
    quantity: 5200,
    unitPrice: 0.25,
    total: 1300,
    status: "Sent",
    createdAt: "2025-11-20T10:00:00Z",
    expectedDelivery: "2025-12-05T17:00:00Z",
    notes: "Cover sheets only. Collect from our premises.",
  },
  {
    id: "VPO-2025-002",
    vendorId: "vendor-finishpro",
    vendorName: "FinishPro Veredlung GmbH",
    orderId: "ORD-2025-005",
    orderNumber: "ORD-2025-005",
    jobTicketId: "JOB-2025-005",
    stepName: "Foil Stamping",
    specs: { type: "Hot foil stamping", foil: "Gold", coverage: "Logo and border on front label" },
    quantity: 25000,
    unitPrice: 0.08,
    total: 2000,
    status: "Completed",
    createdAt: "2025-08-28T10:00:00Z",
    expectedDelivery: "2025-09-05T17:00:00Z",
    actualCost: 1950,
    notes: "Completed on time. Excellent quality.",
  },
  {
    id: "VPO-2025-003",
    vendorId: "vendor-finishpro",
    vendorName: "FinishPro Veredlung GmbH",
    orderId: "ORD-2025-006",
    orderNumber: "ORD-2025-006",
    jobTicketId: "JOB-2025-017",
    stepName: "Spot UV",
    specs: { type: "Selective UV varnish", coverage: "Full front panel of gift box wrap", stock: "150gsm Art Paper" },
    quantity: 3200,
    unitPrice: 0.25,
    total: 800,
    status: "Draft",
    createdAt: "2025-11-28T11:00:00Z",
    expectedDelivery: "2026-01-05T17:00:00Z",
    notes: "On hold — awaiting client sample approval.",
  },
  {
    id: "VPO-2025-004",
    vendorId: "vendor-colourcraft",
    vendorName: "ColourCraft Digital Ltd",
    orderId: "ORD-2025-004",
    orderNumber: "ORD-2025-004",
    jobTicketId: "JOB-2025-016",
    stepName: "Fabric Display Wall",
    specs: { type: "Dye sublimation", size: "3000x2400mm", sides: "Double-sided", quantity: "2 units" },
    quantity: 2,
    unitPrice: 280,
    total: 560,
    status: "Sent",
    createdAt: "2025-11-22T10:00:00Z",
    expectedDelivery: "2025-12-20T17:00:00Z",
    notes: "Double-sided sublimation fabric displays for trade show.",
  },
  {
    id: "VPO-2025-005",
    vendorId: "vendor-scandia-die",
    vendorName: "Scandia Die-Cutting ApS",
    orderId: "ORD-2025-006",
    orderNumber: "ORD-2025-006",
    jobTicketId: "JOB-2025-017",
    stepName: "Die Cutting",
    specs: { type: "Flatbed die cutting", material: "2mm Greyboard", dieRef: "New die — box template TBC" },
    quantity: 3200,
    unitPrice: 0.12,
    total: 384,
    status: "Draft",
    createdAt: "2025-11-28T11:30:00Z",
    expectedDelivery: "2026-01-08T17:00:00Z",
    notes: "New die manufacture included. On hold with client.",
  },
  {
    id: "VPO-2025-006",
    vendorId: "vendor-bindwell",
    vendorName: "Bindwell Buchbinderei AG",
    orderId: "ORD-2025-003",
    orderNumber: "ORD-2025-003",
    jobTicketId: "JOB-2025-003",
    stepName: "Perfect Binding",
    specs: { type: "PUR perfect binding", pages: "96 + cover", stock: "150gsm silk interior, 300gsm art cover", trim: "A4" },
    quantity: 5200,
    unitPrice: 0.55,
    total: 2860,
    status: "In Progress",
    createdAt: "2025-11-15T10:00:00Z",
    expectedDelivery: "2025-12-10T17:00:00Z",
    notes: "Sheets to be delivered after UV coating is complete.",
  },
]
