// @ts-nocheck
import type { WorkflowTemplate } from "@/lib/types"

export const mockWorkflowTemplates: WorkflowTemplate[] = [
  {
    id: "wf-digital",
    name: "Digital Print Workflow",
    description: "Standard workflow for digital press jobs — business cards, flyers, leaflets, stickers",
    category: "Digital",
    steps: [
      { id: "wfs-d-1", name: "Prepress", type: "production", estimatedDuration: 30, isParallel: false, isOptional: false, isConditional: false, color: "#6366f1" },
      { id: "wfs-d-2", name: "Printing", type: "production", estimatedDuration: 120, isParallel: false, isOptional: false, isConditional: false, color: "#3b82f6" },
      { id: "wfs-d-3", name: "Lamination", type: "finishing", estimatedDuration: 60, isParallel: false, isOptional: true, isConditional: true, conditionField: "finish", conditionValue: "lamination", color: "#f59e0b" },
      { id: "wfs-d-4", name: "Cutting", type: "finishing", estimatedDuration: 45, isParallel: false, isOptional: false, isConditional: false, color: "#ef4444" },
      { id: "wfs-d-5", name: "QC", type: "quality", estimatedDuration: 20, isParallel: false, isOptional: false, isConditional: false, color: "#10b981" },
      { id: "wfs-d-6", name: "Packaging", type: "packaging", estimatedDuration: 30, isParallel: false, isOptional: false, isConditional: false, color: "#8b5cf6" },
    ],
    productCategories: ["Business Cards", "Flyers", "Leaflets", "Stickers", "Postcards", "Compliment Slips"],
    isDefault: true,
    createdAt: "2025-01-15T09:00:00Z",
    updatedAt: "2025-06-20T14:00:00Z",
    version: 3,
  },
  {
    id: "wf-offset",
    name: "Offset Print Workflow",
    description: "Full workflow for offset litho jobs — brochures, catalogues, annual reports, booklets",
    category: "Offset",
    steps: [
      { id: "wfs-o-1", name: "Prepress & CTP", type: "production", estimatedDuration: 120, isParallel: false, isOptional: false, isConditional: false, color: "#6366f1" },
      { id: "wfs-o-2", name: "Printing", type: "production", estimatedDuration: 480, isParallel: false, isOptional: false, isConditional: false, color: "#3b82f6" },
      { id: "wfs-o-3", name: "Finishing (Lamination / Spot UV)", type: "finishing", estimatedDuration: 120, isParallel: false, isOptional: true, isConditional: true, conditionField: "finish", conditionValue: "any", color: "#f59e0b" },
      { id: "wfs-o-4", name: "Cutting", type: "finishing", estimatedDuration: 60, isParallel: false, isOptional: false, isConditional: false, color: "#ef4444" },
      { id: "wfs-o-5", name: "Folding", type: "finishing", estimatedDuration: 90, isParallel: false, isOptional: true, isConditional: true, conditionField: "folds", conditionValue: "any", color: "#f97316" },
      { id: "wfs-o-6", name: "Binding", type: "finishing", estimatedDuration: 240, isParallel: false, isOptional: true, isConditional: true, conditionField: "binding", conditionValue: "any", color: "#d946ef" },
      { id: "wfs-o-7", name: "QC", type: "quality", estimatedDuration: 60, isParallel: false, isOptional: false, isConditional: false, color: "#10b981" },
      { id: "wfs-o-8", name: "Packaging", type: "packaging", estimatedDuration: 60, isParallel: false, isOptional: false, isConditional: false, color: "#8b5cf6" },
    ],
    productCategories: ["Brochures", "Catalogues", "Annual Reports", "Booklets", "Magazines", "Posters"],
    isDefault: true,
    createdAt: "2025-01-15T09:00:00Z",
    updatedAt: "2025-08-10T11:00:00Z",
    version: 4,
  },
  {
    id: "wf-large-format",
    name: "Large Format Workflow",
    description: "Workflow for wide-format and signage jobs — banners, posters, display graphics, fabric displays",
    category: "Large Format",
    steps: [
      { id: "wfs-lf-1", name: "Prepress", type: "production", estimatedDuration: 45, isParallel: false, isOptional: false, isConditional: false, color: "#6366f1" },
      { id: "wfs-lf-2", name: "Printing — Rigid/Roll", type: "production", estimatedDuration: 120, isParallel: false, isOptional: false, isConditional: false, color: "#3b82f6" },
      { id: "wfs-lf-3", name: "Printing — Fabric Sublimation", type: "production", estimatedDuration: 90, isParallel: true, isOptional: true, isConditional: true, conditionField: "material", conditionValue: "fabric", color: "#0ea5e9" },
      { id: "wfs-lf-4", name: "Cutting / Trimming", type: "finishing", estimatedDuration: 45, isParallel: false, isOptional: false, isConditional: false, color: "#ef4444" },
      { id: "wfs-lf-5", name: "Finishing (Eyelets / Hemming)", type: "finishing", estimatedDuration: 30, isParallel: false, isOptional: true, isConditional: true, conditionField: "finish", conditionValue: "eyelets", color: "#f59e0b" },
      { id: "wfs-lf-6", name: "Assembly", type: "finishing", estimatedDuration: 60, isParallel: false, isOptional: true, isConditional: true, conditionField: "assembly", conditionValue: "required", color: "#f97316" },
      { id: "wfs-lf-7", name: "QC", type: "quality", estimatedDuration: 20, isParallel: false, isOptional: false, isConditional: false, color: "#10b981" },
      { id: "wfs-lf-8", name: "Packaging", type: "packaging", estimatedDuration: 30, isParallel: false, isOptional: false, isConditional: false, color: "#8b5cf6" },
    ],
    productCategories: ["Roll-Up Banners", "PVC Banners", "Posters (Large)", "Fabric Displays", "Wall Graphics", "Floor Graphics"],
    isDefault: true,
    createdAt: "2025-02-01T09:00:00Z",
    updatedAt: "2025-07-15T10:00:00Z",
    version: 2,
  },
  {
    id: "wf-packaging",
    name: "Packaging Workflow",
    description: "Workflow for structural packaging — rigid boxes, folding cartons, presentation boxes",
    category: "Packaging",
    steps: [
      { id: "wfs-p-1", name: "Prepress & Structural Design", type: "production", estimatedDuration: 180, isParallel: false, isOptional: false, isConditional: false, color: "#6366f1" },
      { id: "wfs-p-2", name: "Printing", type: "production", estimatedDuration: 240, isParallel: false, isOptional: false, isConditional: false, color: "#3b82f6" },
      { id: "wfs-p-3", name: "Finishing (UV / Foil / Emboss)", type: "finishing", estimatedDuration: 180, isParallel: false, isOptional: true, isConditional: true, conditionField: "finish", conditionValue: "any", color: "#f59e0b" },
      { id: "wfs-p-4", name: "Die Cutting", type: "finishing", estimatedDuration: 120, isParallel: false, isOptional: false, isConditional: false, color: "#ef4444" },
      { id: "wfs-p-5", name: "Gluing / Assembly", type: "finishing", estimatedDuration: 300, isParallel: false, isOptional: false, isConditional: false, color: "#f97316" },
      { id: "wfs-p-6", name: "Insert Placement", type: "finishing", estimatedDuration: 180, isParallel: false, isOptional: true, isConditional: true, conditionField: "insert", conditionValue: "required", color: "#d946ef" },
      { id: "wfs-p-7", name: "QC", type: "quality", estimatedDuration: 90, isParallel: false, isOptional: false, isConditional: false, color: "#10b981" },
      { id: "wfs-p-8", name: "Packaging & Palletising", type: "packaging", estimatedDuration: 60, isParallel: false, isOptional: false, isConditional: false, color: "#8b5cf6" },
    ],
    productCategories: ["Rigid Boxes", "Folding Cartons", "Presentation Boxes", "Hang Tags", "Sleeves"],
    isDefault: false,
    createdAt: "2025-03-01T09:00:00Z",
    updatedAt: "2025-09-05T16:00:00Z",
    version: 2,
  },
]
